CREATE OR REPLACE PROCEDURE cse_bi.sp_fact_property_modeldata(ploaddate timestamp)
LANGUAGE plpgsql
AS $$
BEGIN
/* 
Author: Kate Drogaieva 
Purpose: This script populate FACT_HO_LL_MODELDATA 
Comment: Due to back dated transactions it was made as a full refresh. 
Last Modification Date: 
Last Modification Date: 07/06/2020 
Adding Limits for THEFA coverage (On-premises and Away from premises 
12/16/2019 POLICY_CHANGES_ID added from DIM_POLICY_CHANGES 
10/25/2019 Total WP and Losses columns added 
10/03/2019 distinct in final select to eliminate duplication due to a SPINN glitch (more then one transaction with the same SystemId 
09/20/2019 population of CovA_FL - CovC_EC added 
*/
/*1. Grouping and aggregating claims data 
a temp table is used because grouping by modeldata_id is much faster*/
drop table if exists tmp_FACT_HO_LL_MODELDATA_IL;
create temporary table tmp_FACT_HO_LL_MODELDATA_IL as
select
modeldata_id ,
count(distinct Quality_ClaimOk_Flg) Quality_ClaimOk_Flg ,
count(Quality_ClaimPolicyTermJoin_Flg) Quality_ClaimPolicyTermJoin_Flg ,
-- 
sum(isnull(CovA_inc_loss,0)+isnull(CovB_inc_loss,0)+isnull(CovC_inc_loss,0)+isnull(CovD_inc_loss,0)+isnull(CovE_inc_loss,0)+isnull(CovF_inc_loss,0)+isnull(LIAB_inc_loss,0)) Loss,
count(distinct claimnumber) Claim_Count,
-- 
sum(case when CatFlg='Yes' then CovA_inc_loss+CovB_inc_loss+CovC_inc_loss+CovD_inc_loss+CovE_inc_loss+CovF_inc_loss+LIAB_inc_loss else 0 end) Cat_Loss,
count(distinct case when CatFlg='Yes' then claimnumber else null end) Cat_Claim_Count,
/*Inc Loss*/
/*CovA*/
sum(case when NC_Water='Yes' then CovA_inc_loss else 0 end) CovA_IL_NC_Water ,
sum(case when NC_WH='Yes' then CovA_inc_loss else 0 end) CovA_IL_NC_WH ,
sum(case when NC_TV='Yes' then CovA_inc_loss else 0 end) CovA_IL_NC_TV ,
sum(case when NC_FL='Yes' then CovA_inc_loss else 0 end) CovA_IL_NC_FL ,
sum(case when NC_AO='Yes' then CovA_inc_loss else 0 end) CovA_IL_NC_AO ,
sum(case when CAT_FL='Yes' then CovA_inc_loss else 0 end) CovA_IL_Cat_Fire ,
sum(case when CAT_AO='Yes' then CovA_inc_loss else 0 end) CovA_IL_Cat_AO ,
/*CovB*/
sum(case when NC_Water='Yes' then CovB_inc_loss else 0 end) CovB_IL_NC_Water ,
sum(case when NC_WH='Yes' then CovB_inc_loss else 0 end) CovB_IL_NC_WH ,
sum(case when NC_TV='Yes' then CovB_inc_loss else 0 end) CovB_IL_NC_TV ,
sum(case when NC_FL='Yes' then CovB_inc_loss else 0 end) CovB_IL_NC_FL ,
sum(case when NC_AO='Yes' then CovB_inc_loss else 0 end) CovB_IL_NC_AO ,
sum(case when CAT_FL='Yes' then CovB_inc_loss else 0 end) CovB_IL_Cat_Fire ,
sum(case when CAT_AO='Yes' then CovB_inc_loss else 0 end) CovB_IL_Cat_AO ,
/*CovC*/
sum(case when NC_Water='Yes' then CovC_inc_loss else 0 end) CovC_IL_NC_Water ,
sum(case when NC_WH='Yes' then CovC_inc_loss else 0 end) CovC_IL_NC_WH ,
sum(case when NC_TV='Yes' then CovC_inc_loss else 0 end) CovC_IL_NC_TV ,
sum(case when NC_FL='Yes' then CovC_inc_loss else 0 end) CovC_IL_NC_FL ,
sum(case when NC_AO='Yes' then CovC_inc_loss else 0 end) CovC_IL_NC_AO ,
sum(case when CAT_FL='Yes' then CovC_inc_loss else 0 end) CovC_IL_Cat_Fire ,
sum(case when CAT_AO='Yes' then CovC_inc_loss else 0 end) CovC_IL_Cat_AO ,
/*CovD*/
sum(case when NC_Water='Yes' then CovD_inc_loss else 0 end) CovD_IL_NC_Water ,
sum(case when NC_WH='Yes' then CovD_inc_loss else 0 end) CovD_IL_NC_WH ,
sum(case when NC_TV='Yes' then CovD_inc_loss else 0 end) CovD_IL_NC_TV ,
sum(case when NC_FL='Yes' then CovD_inc_loss else 0 end) CovD_IL_NC_FL ,
sum(case when NC_AO='Yes' then CovD_inc_loss else 0 end) CovD_IL_NC_AO ,
sum(case when CAT_FL='Yes' then CovD_inc_loss else 0 end) CovD_IL_Cat_Fire ,
sum(case when CAT_AO='Yes' then CovD_inc_loss else 0 end) CovD_IL_Cat_AO ,
/*CovE*/
sum(case when NC_Water='Yes' then CovE_inc_loss else 0 end) CovE_IL_NC_Water ,
sum(case when NC_WH='Yes' then CovE_inc_loss else 0 end) CovE_IL_NC_WH ,
sum(case when NC_TV='Yes' then CovE_inc_loss else 0 end) CovE_IL_NC_TV ,
sum(case when NC_FL='Yes' then CovE_inc_loss else 0 end) CovE_IL_NC_FL ,
sum(case when NC_AO='Yes' then CovE_inc_loss else 0 end) CovE_IL_NC_AO ,
sum(case when CAT_FL='Yes' then CovE_inc_loss else 0 end) CovE_IL_Cat_Fire ,
sum(case when CAT_AO='Yes' then CovE_inc_loss else 0 end) CovE_IL_Cat_AO ,
/*CovF*/
sum(case when NC_Water='Yes' then CovF_inc_loss else 0 end) CovF_IL_NC_Water ,
sum(case when NC_WH='Yes' then CovF_inc_loss else 0 end) CovF_IL_NC_WH ,
sum(case when NC_TV='Yes' then CovF_inc_loss else 0 end) CovF_IL_NC_TV ,
sum(case when NC_FL='Yes' then CovF_inc_loss else 0 end) CovF_IL_NC_FL ,
sum(case when NC_AO='Yes' then CovF_inc_loss else 0 end) CovF_IL_NC_AO ,
sum(case when CAT_FL='Yes' then CovF_inc_loss else 0 end) CovF_IL_Cat_Fire ,
sum(case when CAT_AO='Yes' then CovF_inc_loss else 0 end) CovF_IL_Cat_AO ,
/*LIAB*/
sum(case when NC_Water='Yes' then LIAB_inc_loss else 0 end) LIAB_IL_NC_Water ,
sum(case when NC_WH='Yes' then LIAB_inc_loss else 0 end) LIAB_IL_NC_WH ,
sum(case when NC_TV='Yes' then LIAB_inc_loss else 0 end) LIAB_IL_NC_TV ,
sum(case when NC_FL='Yes' then LIAB_inc_loss else 0 end) LIAB_IL_NC_FL ,
sum(case when NC_AO='Yes' then LIAB_inc_loss else 0 end) LIAB_IL_NC_AO ,
sum(case when CAT_FL='Yes' then LIAB_inc_loss else 0 end) LIAB_IL_Cat_Fire ,
sum(case when CAT_AO='Yes' then LIAB_inc_loss else 0 end) LIAB_IL_Cat_AO ,
/*Inc Loss + DCCE*/
/*CovA*/
sum(case when NC_Water='Yes' then CovA_inc_loss + CovA_dcce else 0 end) CovA_IL_DCCE_NC_Water ,
sum(case when NC_WH='Yes' then CovA_inc_loss+CovA_dcce else 0 end) CovA_IL_DCCE_NC_WH ,
sum(case when NC_TV='Yes' then CovA_inc_loss+CovA_dcce else 0 end) CovA_IL_DCCE_NC_TV ,
sum(case when NC_FL='Yes' then CovA_inc_loss+CovA_dcce else 0 end) CovA_IL_DCCE_NC_FL ,
sum(case when NC_AO='Yes' then CovA_inc_loss+CovA_dcce else 0 end) CovA_IL_DCCE_NC_AO ,
sum(case when CAT_FL='Yes' then CovA_inc_loss+CovA_dcce else 0 end) CovA_IL_DCCE_Cat_Fire ,
sum(case when CAT_AO='Yes' then CovA_inc_loss+CovA_dcce else 0 end) CovA_IL_DCCE_Cat_AO ,
/*CovB*/
sum(case when NC_Water='Yes' then CovB_inc_loss + CovB_dcce else 0 end) CovB_IL_DCCE_NC_Water ,
sum(case when NC_WH='Yes' then CovB_inc_loss+CovB_dcce else 0 end) CovB_IL_DCCE_NC_WH ,
sum(case when NC_TV='Yes' then CovB_inc_loss+CovB_dcce else 0 end) CovB_IL_DCCE_NC_TV ,
sum(case when NC_FL='Yes' then CovB_inc_loss+CovB_dcce else 0 end) CovB_IL_DCCE_NC_FL ,
sum(case when NC_AO='Yes' then CovB_inc_loss+CovB_dcce else 0 end) CovB_IL_DCCE_NC_AO ,
sum(case when CAT_FL='Yes' then CovB_inc_loss+CovB_dcce else 0 end) CovB_IL_DCCE_Cat_Fire ,
sum(case when CAT_AO='Yes' then CovB_inc_loss+CovB_dcce else 0 end) CovB_IL_DCCE_Cat_AO ,
/*CovC*/
sum(case when NC_Water='Yes' then CovC_inc_loss + CovC_dcce else 0 end) CovC_IL_DCCE_NC_Water ,
sum(case when NC_WH='Yes' then CovC_inc_loss+CovC_dcce else 0 end) CovC_IL_DCCE_NC_WH ,
sum(case when NC_TV='Yes' then CovC_inc_loss+CovC_dcce else 0 end) CovC_IL_DCCE_NC_TV ,
sum(case when NC_FL='Yes' then CovC_inc_loss+CovC_dcce else 0 end) CovC_IL_DCCE_NC_FL ,
sum(case when NC_AO='Yes' then CovC_inc_loss+CovC_dcce else 0 end) CovC_IL_DCCE_NC_AO ,
sum(case when CAT_FL='Yes' then CovC_inc_loss+CovC_dcce else 0 end) CovC_IL_DCCE_Cat_Fire ,
sum(case when CAT_AO='Yes' then CovC_inc_loss+CovC_dcce else 0 end) CovC_IL_DCCE_Cat_AO ,
/*CovD*/
sum(case when NC_Water='Yes' then CovD_inc_loss + CovD_dcce else 0 end) CovD_IL_DCCE_NC_Water ,
sum(case when NC_WH='Yes' then CovD_inc_loss+CovD_dcce else 0 end) CovD_IL_DCCE_NC_WH ,
sum(case when NC_TV='Yes' then CovD_inc_loss+CovD_dcce else 0 end) CovD_IL_DCCE_NC_TV ,
sum(case when NC_FL='Yes' then CovD_inc_loss+CovD_dcce else 0 end) CovD_IL_DCCE_NC_FL ,
sum(case when NC_AO='Yes' then CovD_inc_loss+CovD_dcce else 0 end) CovD_IL_DCCE_NC_AO ,
sum(case when CAT_FL='Yes' then CovD_inc_loss+CovD_dcce else 0 end) CovD_IL_DCCE_Cat_Fire ,
sum(case when CAT_AO='Yes' then CovD_inc_loss+CovD_dcce else 0 end) CovD_IL_DCCE_Cat_AO ,
/*CovE*/
sum(case when NC_Water='Yes' then CovE_inc_loss + CovE_dcce else 0 end) CovE_IL_DCCE_NC_Water ,
sum(case when NC_WH='Yes' then CovE_inc_loss+CovE_dcce else 0 end) CovE_IL_DCCE_NC_WH ,
sum(case when NC_TV='Yes' then CovE_inc_loss+CovE_dcce else 0 end) CovE_IL_DCCE_NC_TV ,
sum(case when NC_FL='Yes' then CovE_inc_loss+CovE_dcce else 0 end) CovE_IL_DCCE_NC_FL ,
sum(case when NC_AO='Yes' then CovE_inc_loss+CovE_dcce else 0 end) CovE_IL_DCCE_NC_AO ,
sum(case when CAT_FL='Yes' then CovE_inc_loss+CovE_dcce else 0 end) CovE_IL_DCCE_Cat_Fire ,
sum(case when CAT_AO='Yes' then CovE_inc_loss+CovE_dcce else 0 end) CovE_IL_DCCE_Cat_AO ,
/*CovF*/
sum(case when NC_Water='Yes' then CovF_inc_loss + CovF_dcce else 0 end) CovF_IL_DCCE_NC_Water ,
sum(case when NC_WH='Yes' then CovF_inc_loss+CovF_dcce else 0 end) CovF_IL_DCCE_NC_WH ,
sum(case when NC_TV='Yes' then CovF_inc_loss+CovF_dcce else 0 end) CovF_IL_DCCE_NC_TV ,
sum(case when NC_FL='Yes' then CovF_inc_loss+CovF_dcce else 0 end) CovF_IL_DCCE_NC_FL ,
sum(case when NC_AO='Yes' then CovF_inc_loss+CovF_dcce else 0 end) CovF_IL_DCCE_NC_AO ,
sum(case when CAT_FL='Yes' then CovF_inc_loss+CovF_dcce else 0 end) CovF_IL_DCCE_Cat_Fire ,
sum(case when CAT_AO='Yes' then CovF_inc_loss+CovF_dcce else 0 end) CovF_IL_DCCE_Cat_AO ,
/*LIAB*/
sum(case when NC_Water='Yes' then LIAB_inc_loss + LIAB_dcce else 0 end) LIAB_IL_DCCE_NC_Water ,
sum(case when NC_WH='Yes' then LIAB_inc_loss+LIAB_dcce else 0 end) LIAB_IL_DCCE_NC_WH ,
sum(case when NC_TV='Yes' then LIAB_inc_loss+LIAB_dcce else 0 end) LIAB_IL_DCCE_NC_TV ,
sum(case when NC_FL='Yes' then LIAB_inc_loss+LIAB_dcce else 0 end) LIAB_IL_DCCE_NC_FL ,
sum(case when NC_AO='Yes' then LIAB_inc_loss+LIAB_dcce else 0 end) LIAB_IL_DCCE_NC_AO ,
sum(case when CAT_FL='Yes' then LIAB_inc_loss+LIAB_dcce else 0 end) LIAB_IL_DCCE_Cat_Fire ,
sum(case when CAT_AO='Yes' then LIAB_inc_loss+LIAB_dcce else 0 end) LIAB_IL_DCCE_Cat_AO ,
/*Inc Loss + ALAE*/
/*CovA*/
sum(case when NC_Water='Yes' then CovA_inc_loss + CovA_alae else 0 end) CovA_IL_ALAE_NC_Water ,
sum(case when NC_WH='Yes' then CovA_inc_loss+CovA_alae else 0 end) CovA_IL_ALAE_NC_WH ,
sum(case when NC_TV='Yes' then CovA_inc_loss+CovA_alae else 0 end) CovA_IL_ALAE_NC_TV ,
sum(case when NC_FL='Yes' then CovA_inc_loss+CovA_alae else 0 end) CovA_IL_ALAE_NC_FL ,
sum(case when NC_AO='Yes' then CovA_inc_loss+CovA_alae else 0 end) CovA_IL_ALAE_NC_AO ,
sum(case when CAT_FL='Yes' then CovA_inc_loss+CovA_alae else 0 end) CovA_IL_ALAE_Cat_Fire ,
sum(case when CAT_AO='Yes' then CovA_inc_loss+CovA_alae else 0 end) CovA_IL_ALAE_Cat_AO ,
/*CovB*/
sum(case when NC_Water='Yes' then CovB_inc_loss + CovB_alae else 0 end) CovB_IL_ALAE_NC_Water ,
sum(case when NC_WH='Yes' then CovB_inc_loss+CovB_alae else 0 end) CovB_IL_ALAE_NC_WH ,
sum(case when NC_TV='Yes' then CovB_inc_loss+CovB_alae else 0 end) CovB_IL_ALAE_NC_TV ,
sum(case when NC_FL='Yes' then CovB_inc_loss+CovB_alae else 0 end) CovB_IL_ALAE_NC_FL ,
sum(case when NC_AO='Yes' then CovB_inc_loss+CovB_alae else 0 end) CovB_IL_ALAE_NC_AO ,
sum(case when CAT_FL='Yes' then CovB_inc_loss+CovB_alae else 0 end) CovB_IL_ALAE_Cat_Fire ,
sum(case when CAT_AO='Yes' then CovB_inc_loss+CovB_alae else 0 end) CovB_IL_ALAE_Cat_AO ,
/*CovC*/
sum(case when NC_Water='Yes' then CovC_inc_loss + CovC_alae else 0 end) CovC_IL_ALAE_NC_Water ,
sum(case when NC_WH='Yes' then CovC_inc_loss+CovC_alae else 0 end) CovC_IL_ALAE_NC_WH ,
sum(case when NC_TV='Yes' then CovC_inc_loss+CovC_alae else 0 end) CovC_IL_ALAE_NC_TV ,
sum(case when NC_FL='Yes' then CovC_inc_loss+CovC_alae else 0 end) CovC_IL_ALAE_NC_FL ,
sum(case when NC_AO='Yes' then CovC_inc_loss+CovC_alae else 0 end) CovC_IL_ALAE_NC_AO ,
sum(case when CAT_FL='Yes' then CovC_inc_loss+CovC_alae else 0 end) CovC_IL_ALAE_Cat_Fire ,
sum(case when CAT_AO='Yes' then CovC_inc_loss+CovC_alae else 0 end) CovC_IL_ALAE_Cat_AO ,
/*CovD*/
sum(case when NC_Water='Yes' then CovD_inc_loss + CovD_alae else 0 end) CovD_IL_ALAE_NC_Water ,
sum(case when NC_WH='Yes' then CovD_inc_loss+CovD_alae else 0 end) CovD_IL_ALAE_NC_WH ,
sum(case when NC_TV='Yes' then CovD_inc_loss+CovD_alae else 0 end) CovD_IL_ALAE_NC_TV ,
sum(case when NC_FL='Yes' then CovD_inc_loss+CovD_alae else 0 end) CovD_IL_ALAE_NC_FL ,
sum(case when NC_AO='Yes' then CovD_inc_loss+CovD_alae else 0 end) CovD_IL_ALAE_NC_AO ,
sum(case when CAT_FL='Yes' then CovD_inc_loss+CovD_alae else 0 end) CovD_IL_ALAE_Cat_Fire ,
sum(case when CAT_AO='Yes' then CovD_inc_loss+CovD_alae else 0 end) CovD_IL_ALAE_Cat_AO ,
/*CovE*/
sum(case when NC_Water='Yes' then CovE_inc_loss + CovE_alae else 0 end) CovE_IL_ALAE_NC_Water ,
sum(case when NC_WH='Yes' then CovE_inc_loss+CovE_alae else 0 end) CovE_IL_ALAE_NC_WH ,
sum(case when NC_TV='Yes' then CovE_inc_loss+CovE_alae else 0 end) CovE_IL_ALAE_NC_TV ,
sum(case when NC_FL='Yes' then CovE_inc_loss+CovE_alae else 0 end) CovE_IL_ALAE_NC_FL ,
sum(case when NC_AO='Yes' then CovE_inc_loss+CovE_alae else 0 end) CovE_IL_ALAE_NC_AO ,
sum(case when CAT_FL='Yes' then CovE_inc_loss+CovE_alae else 0 end) CovE_IL_ALAE_Cat_Fire ,
sum(case when CAT_AO='Yes' then CovE_inc_loss+CovE_alae else 0 end) CovE_IL_ALAE_Cat_AO ,
/*CovF*/
sum(case when NC_Water='Yes' then CovF_inc_loss + CovF_alae else 0 end) CovF_IL_ALAE_NC_Water ,
sum(case when NC_WH='Yes' then CovF_inc_loss+CovF_alae else 0 end) CovF_IL_ALAE_NC_WH ,
sum(case when NC_TV='Yes' then CovF_inc_loss+CovF_alae else 0 end) CovF_IL_ALAE_NC_TV ,
sum(case when NC_FL='Yes' then CovF_inc_loss+CovF_alae else 0 end) CovF_IL_ALAE_NC_FL ,
sum(case when NC_AO='Yes' then CovF_inc_loss+CovF_alae else 0 end) CovF_IL_ALAE_NC_AO ,
sum(case when CAT_FL='Yes' then CovF_inc_loss+CovF_alae else 0 end) CovF_IL_ALAE_Cat_Fire ,
sum(case when CAT_AO='Yes' then CovF_inc_loss+CovF_alae else 0 end) CovF_IL_ALAE_Cat_AO ,
/*LIAB*/
sum(case when NC_Water='Yes' then LIAB_inc_loss + LIAB_alae else 0 end) LIAB_IL_ALAE_NC_Water ,
sum(case when NC_WH='Yes' then LIAB_inc_loss+LIAB_alae else 0 end) LIAB_IL_ALAE_NC_WH ,
sum(case when NC_TV='Yes' then LIAB_inc_loss+LIAB_alae else 0 end) LIAB_IL_ALAE_NC_TV ,
sum(case when NC_FL='Yes' then LIAB_inc_loss+LIAB_alae else 0 end) LIAB_IL_ALAE_NC_FL ,
sum(case when NC_AO='Yes' then LIAB_inc_loss+LIAB_alae else 0 end) LIAB_IL_ALAE_NC_AO ,
sum(case when CAT_FL='Yes' then LIAB_inc_loss+LIAB_alae else 0 end) LIAB_IL_ALAE_Cat_Fire ,
sum(case when CAT_AO='Yes' then LIAB_inc_loss+LIAB_alae else 0 end) LIAB_IL_ALAE_Cat_AO ,
sum(CovA_FL) CovA_FL,
sum(CovA_SF) CovA_SF,
sum(CovA_EC) CovA_EC,
sum(CovC_FL) CovC_FL,
sum(CovC_SF) CovC_SF,
sum(CovC_EC) CovC_EC,
sum(isnull(all_lossinc,0)) AllCov_LossInc,
sum(isnull(all_dcce,0)) AllCov_LossDCCE,
sum(isnull(all_alae,0)) AllCov_LossALAE
from fsbi_stg_spinn.STG_PROPERTY_MODELDATA stg
join fsbi_stg_spinn.vstg_property_modeldata_claims c
on stg.claimrisk_id=c.claimrisk_id
group by
modeldata_id;
/* Counts */
drop table if exists tmp_FACT_HO_LL_MODELDATA_IC;
create temporary table tmp_FACT_HO_LL_MODELDATA_IC as
select
modeldata_id ,
/*Inc Loss*/
/*CovA*/
sum( case when NC_Water='Yes' and CovA_inc_loss >0 then 1 else 0 end) CovA_IC_NC_Water ,
sum( case when NC_WH='Yes' and CovA_inc_loss >0 then 1 else 0 end) CovA_IC_NC_WH ,
sum( case when NC_TV='Yes' and CovA_inc_loss >0 then 1 else 0 end) CovA_IC_NC_TV ,
sum( case when NC_FL='Yes' and CovA_inc_loss >0 then 1 else 0 end) CovA_IC_NC_FL ,
sum( case when NC_AO='Yes' and CovA_inc_loss >0 then 1 else 0 end) CovA_IC_NC_AO ,
sum( case when CAT_FL='Yes' and CovA_inc_loss >0 then 1 else 0 end) CovA_IC_Cat_Fire ,
sum( case when CAT_AO='Yes' and CovA_inc_loss >0 then 1 else 0 end) CovA_IC_Cat_AO ,
/*CovB*/
sum( case when NC_Water='Yes' and CovB_inc_loss >0 then 1 else 0 end) CovB_IC_NC_Water ,
sum( case when NC_WH='Yes' and CovB_inc_loss >0 then 1 else 0 end) CovB_IC_NC_WH ,
sum( case when NC_TV='Yes' and CovB_inc_loss >0 then 1 else 0 end) CovB_IC_NC_TV ,
sum( case when NC_FL='Yes' and CovB_inc_loss >0 then 1 else 0 end) CovB_IC_NC_FL ,
sum( case when NC_AO='Yes' and CovB_inc_loss >0 then 1 else 0 end) CovB_IC_NC_AO ,
sum( case when CAT_FL='Yes' and CovB_inc_loss >0 then 1 else 0 end) CovB_IC_Cat_Fire ,
sum( case when CAT_AO='Yes' and CovB_inc_loss >0 then 1 else 0 end) CovB_IC_Cat_AO ,
/*CovC*/
sum( case when NC_Water='Yes' and CovC_inc_loss >0 then 1 else 0 end) CovC_IC_NC_Water ,
sum( case when NC_WH='Yes' and CovC_inc_loss >0 then 1 else 0 end) CovC_IC_NC_WH ,
sum( case when NC_TV='Yes' and CovC_inc_loss >0 then 1 else 0 end) CovC_IC_NC_TV ,
sum( case when NC_FL='Yes' and CovC_inc_loss >0 then 1 else 0 end) CovC_IC_NC_FL ,
sum( case when NC_AO='Yes' and CovC_inc_loss >0 then 1 else 0 end) CovC_IC_NC_AO ,
sum( case when CAT_FL='Yes' and CovC_inc_loss >0 then 1 else 0 end) CovC_IC_Cat_Fire ,
sum( case when CAT_AO='Yes' and CovC_inc_loss >0 then 1 else 0 end) CovC_IC_Cat_AO ,
/*CovD*/
sum( case when NC_Water='Yes' and CovD_inc_loss >0 then 1 else 0 end) CovD_IC_NC_Water ,
sum( case when NC_WH='Yes' and CovD_inc_loss >0 then 1 else 0 end) CovD_IC_NC_WH ,
sum( case when NC_TV='Yes' and CovD_inc_loss >0 then 1 else 0 end) CovD_IC_NC_TV ,
sum( case when NC_FL='Yes' and CovD_inc_loss >0 then 1 else 0 end) CovD_IC_NC_FL ,
sum( case when NC_AO='Yes' and CovD_inc_loss >0 then 1 else 0 end) CovD_IC_NC_AO ,
sum( case when CAT_FL='Yes' and CovD_inc_loss >0 then 1 else 0 end) CovD_IC_Cat_Fire ,
sum( case when CAT_AO='Yes' and CovD_inc_loss >0 then 1 else 0 end) CovD_IC_Cat_AO ,
sum( case when NC_Water='Yes' and CovE_inc_loss >0 then 1 else 0 end) CovE_IC_NC_Water ,
sum( case when NC_WH='Yes' and CovE_inc_loss >0 then 1 else 0 end) CovE_IC_NC_WH ,
sum( case when NC_TV='Yes' and CovE_inc_loss >0 then 1 else 0 end) CovE_IC_NC_TV ,
sum( case when NC_FL='Yes' and CovE_inc_loss >0 then 1 else 0 end) CovE_IC_NC_FL ,
sum( case when NC_AO='Yes' and CovE_inc_loss >0 then 1 else 0 end) CovE_IC_NC_AO ,
sum( case when CAT_FL='Yes' and CovE_inc_loss >0 then 1 else 0 end) CovE_IC_Cat_Fire ,
sum( case when CAT_AO='Yes' and CovE_inc_loss >0 then 1 else 0 end) CovE_IC_Cat_AO ,
/*CovF*/
sum( case when NC_Water='Yes' and CovF_inc_loss >0 then 1 else 0 end) CovF_IC_NC_Water ,
sum( case when NC_WH='Yes' and CovF_inc_loss >0 then 1 else 0 end) CovF_IC_NC_WH ,
sum( case when NC_TV='Yes' and CovF_inc_loss >0 then 1 else 0 end) CovF_IC_NC_TV ,
sum( case when NC_FL='Yes' and CovF_inc_loss >0 then 1 else 0 end) CovF_IC_NC_FL ,
sum( case when NC_AO='Yes' and CovF_inc_loss >0 then 1 else 0 end) CovF_IC_NC_AO ,
sum( case when CAT_FL='Yes' and CovF_inc_loss >0 then 1 else 0 end) CovF_IC_Cat_Fire ,
sum( case when CAT_AO='Yes' and CovF_inc_loss >0 then 1 else 0 end) CovF_IC_Cat_AO ,
/*LIAB*/
sum( case when NC_Water='Yes' and LIAB_inc_loss >0 then 1 else 0 end) LIAB_IC_NC_Water ,
sum( case when NC_WH='Yes' and LIAB_inc_loss >0 then 1 else 0 end) LIAB_IC_NC_WH ,
sum( case when NC_TV='Yes' and LIAB_inc_loss >0 then 1 else 0 end) LIAB_IC_NC_TV ,
sum( case when NC_FL='Yes' and LIAB_inc_loss >0 then 1 else 0 end) LIAB_IC_NC_FL ,
sum( case when NC_AO='Yes' and LIAB_inc_loss >0 then 1 else 0 end) LIAB_IC_NC_AO ,
sum( case when CAT_FL='Yes' and LIAB_inc_loss >0 then 1 else 0 end) LIAB_IC_Cat_Fire ,
sum( case when CAT_AO='Yes' and LIAB_inc_loss >0 then 1 else 0 end) LIAB_IC_Cat_AO ,
/*Inc Loss + DCCE*/
/*CovA*/
sum( case when NC_Water='Yes' and CovA_inc_loss + CovA_dcce >0 then 1 else 0 end) CovA_IC_DCCE_NC_Water ,
sum( case when NC_WH='Yes' and CovA_inc_loss+CovA_dcce >0 then 1 else 0 end) CovA_IC_DCCE_NC_WH ,
sum( case when NC_TV='Yes' and CovA_inc_loss+CovA_dcce >0 then 1 else 0 end) CovA_IC_DCCE_NC_TV ,
sum( case when NC_FL='Yes' and CovA_inc_loss+CovA_dcce >0 then 1 else 0 end) CovA_IC_DCCE_NC_FL ,
sum( case when NC_AO='Yes' and CovA_inc_loss+CovA_dcce >0 then 1 else 0 end) CovA_IC_DCCE_NC_AO ,
sum( case when CAT_FL='Yes' and CovA_inc_loss+CovA_dcce >0 then 1 else 0 end) CovA_IC_DCCE_Cat_Fire ,
sum( case when CAT_AO='Yes' and CovA_inc_loss+CovA_dcce >0 then 1 else 0 end) CovA_IC_DCCE_Cat_AO ,
/*CovB*/
sum( case when NC_Water='Yes' and CovB_inc_loss + CovB_dcce >0 then 1 else 0 end) CovB_IC_DCCE_NC_Water ,
sum( case when NC_WH='Yes' and CovB_inc_loss+CovB_dcce >0 then 1 else 0 end) CovB_IC_DCCE_NC_WH ,
sum( case when NC_TV='Yes' and CovB_inc_loss+CovB_dcce >0 then 1 else 0 end) CovB_IC_DCCE_NC_TV ,
sum( case when NC_FL='Yes' and CovB_inc_loss+CovB_dcce >0 then 1 else 0 end) CovB_IC_DCCE_NC_FL ,
sum( case when NC_AO='Yes' and CovB_inc_loss+CovB_dcce >0 then 1 else 0 end) CovB_IC_DCCE_NC_AO ,
sum( case when CAT_FL='Yes' and CovB_inc_loss+CovB_dcce >0 then 1 else 0 end) CovB_IC_DCCE_Cat_Fire ,
sum( case when CAT_AO='Yes' and CovB_inc_loss+CovB_dcce >0 then 1 else 0 end) CovB_IC_DCCE_Cat_AO ,
/*CovC*/
sum( case when NC_Water='Yes' and CovC_inc_loss + CovC_dcce >0 then 1 else 0 end) CovC_IC_DCCE_NC_Water ,
sum( case when NC_WH='Yes' and CovC_inc_loss+CovC_dcce >0 then 1 else 0 end) CovC_IC_DCCE_NC_WH ,
sum( case when NC_TV='Yes' and CovC_inc_loss+CovC_dcce >0 then 1 else 0 end) CovC_IC_DCCE_NC_TV ,
sum( case when NC_FL='Yes' and CovC_inc_loss+CovC_dcce >0 then 1 else 0 end) CovC_IC_DCCE_NC_FL ,
sum( case when NC_AO='Yes' and CovC_inc_loss+CovC_dcce >0 then 1 else 0 end) CovC_IC_DCCE_NC_AO ,
sum( case when CAT_FL='Yes' and CovC_inc_loss+CovC_dcce >0 then 1 else 0 end) CovC_IC_DCCE_Cat_Fire ,
sum( case when CAT_AO='Yes' and CovC_inc_loss+CovC_dcce >0 then 1 else 0 end) CovC_IC_DCCE_Cat_AO ,
/*CovD*/
sum( case when NC_Water='Yes' and CovD_inc_loss + CovD_dcce >0 then 1 else 0 end) CovD_IC_DCCE_NC_Water ,
sum( case when NC_WH='Yes' and CovD_inc_loss+CovD_dcce >0 then 1 else 0 end) CovD_IC_DCCE_NC_WH ,
sum( case when NC_TV='Yes' and CovD_inc_loss+CovD_dcce >0 then 1 else 0 end) CovD_IC_DCCE_NC_TV ,
sum( case when NC_FL='Yes' and CovD_inc_loss+CovD_dcce >0 then 1 else 0 end) CovD_IC_DCCE_NC_FL ,
sum( case when NC_AO='Yes' and CovD_inc_loss+CovD_dcce >0 then 1 else 0 end) CovD_IC_DCCE_NC_AO ,
sum( case when CAT_FL='Yes' and CovD_inc_loss+CovD_dcce >0 then 1 else 0 end) CovD_IC_DCCE_Cat_Fire ,
sum( case when CAT_AO='Yes' and CovD_inc_loss+CovD_dcce >0 then 1 else 0 end) CovD_IC_DCCE_Cat_AO ,
sum( case when NC_Water='Yes' and CovE_inc_loss + CovE_dcce >0 then 1 else 0 end) CovE_IC_DCCE_NC_Water ,
sum( case when NC_WH='Yes' and CovE_inc_loss+CovE_dcce >0 then 1 else 0 end) CovE_IC_DCCE_NC_WH ,
sum( case when NC_TV='Yes' and CovE_inc_loss+CovE_dcce >0 then 1 else 0 end) CovE_IC_DCCE_NC_TV ,
sum( case when NC_FL='Yes' and CovE_inc_loss+CovE_dcce >0 then 1 else 0 end) CovE_IC_DCCE_NC_FL ,
sum( case when NC_AO='Yes' and CovE_inc_loss+CovE_dcce >0 then 1 else 0 end) CovE_IC_DCCE_NC_AO ,
sum( case when CAT_FL='Yes' and CovE_inc_loss+CovE_dcce >0 then 1 else 0 end) CovE_IC_DCCE_Cat_Fire ,
sum( case when CAT_AO='Yes' and CovE_inc_loss+CovE_dcce >0 then 1 else 0 end) CovE_IC_DCCE_Cat_AO ,
/*CovF*/
sum( case when NC_Water='Yes' and CovF_inc_loss + CovF_dcce >0 then 1 else 0 end) CovF_IC_DCCE_NC_Water ,
sum( case when NC_WH='Yes' and CovF_inc_loss+CovF_dcce >0 then 1 else 0 end) CovF_IC_DCCE_NC_WH ,
sum( case when NC_TV='Yes' and CovF_inc_loss+CovF_dcce >0 then 1 else 0 end) CovF_IC_DCCE_NC_TV ,
sum( case when NC_FL='Yes' and CovF_inc_loss+CovF_dcce >0 then 1 else 0 end) CovF_IC_DCCE_NC_FL ,
sum( case when NC_AO='Yes' and CovF_inc_loss+CovF_dcce >0 then 1 else 0 end) CovF_IC_DCCE_NC_AO ,
sum( case when CAT_FL='Yes' and CovF_inc_loss+CovF_dcce >0 then 1 else 0 end) CovF_IC_DCCE_Cat_Fire ,
sum( case when CAT_AO='Yes' and CovF_inc_loss+CovF_dcce >0 then 1 else 0 end) CovF_IC_DCCE_Cat_AO ,
/*LIAB*/
sum( case when NC_Water='Yes' and LIAB_inc_loss + LIAB_dcce >0 then 1 else 0 end) LIAB_IC_DCCE_NC_Water ,
sum( case when NC_WH='Yes' and LIAB_inc_loss+LIAB_dcce >0 then 1 else 0 end) LIAB_IC_DCCE_NC_WH ,
sum( case when NC_TV='Yes' and LIAB_inc_loss+LIAB_dcce >0 then 1 else 0 end) LIAB_IC_DCCE_NC_TV ,
sum( case when NC_FL='Yes' and LIAB_inc_loss+LIAB_dcce >0 then 1 else 0 end) LIAB_IC_DCCE_NC_FL ,
sum( case when NC_AO='Yes' and LIAB_inc_loss+LIAB_dcce >0 then 1 else 0 end) LIAB_IC_DCCE_NC_AO ,
sum( case when CAT_FL='Yes' and LIAB_inc_loss+LIAB_dcce >0 then 1 else 0 end) LIAB_IC_DCCE_Cat_Fire ,
sum( case when CAT_AO='Yes' and LIAB_inc_loss+LIAB_dcce >0 then 1 else 0 end) LIAB_IC_DCCE_Cat_AO ,
/*Inc Loss + ALAE*/
/*CovA*/
sum( case when NC_Water='Yes' and CovA_inc_loss + CovA_alae >0 then 1 else 0 end) CovA_IC_ALAE_NC_Water ,
sum( case when NC_WH='Yes' and CovA_inc_loss+CovA_alae >0 then 1 else 0 end) CovA_IC_ALAE_NC_WH ,
sum( case when NC_TV='Yes' and CovA_inc_loss+CovA_alae >0 then 1 else 0 end) CovA_IC_ALAE_NC_TV ,
sum( case when NC_FL='Yes' and CovA_inc_loss+CovA_alae >0 then 1 else 0 end) CovA_IC_ALAE_NC_FL ,
sum( case when NC_AO='Yes' and CovA_inc_loss+CovA_alae >0 then 1 else 0 end) CovA_IC_ALAE_NC_AO ,
sum( case when CAT_FL='Yes' and CovA_inc_loss+CovA_alae >0 then 1 else 0 end) CovA_IC_ALAE_Cat_Fire ,
sum( case when CAT_AO='Yes' and CovA_inc_loss+CovA_alae >0 then 1 else 0 end) CovA_IC_ALAE_Cat_AO ,
/*CovB*/
sum( case when NC_Water='Yes' and CovB_inc_loss + CovB_alae >0 then 1 else 0 end) CovB_IC_ALAE_NC_Water ,
sum( case when NC_WH='Yes' and CovB_inc_loss+CovB_alae >0 then 1 else 0 end) CovB_IC_ALAE_NC_WH ,
sum( case when NC_TV='Yes' and CovB_inc_loss+CovB_alae >0 then 1 else 0 end) CovB_IC_ALAE_NC_TV ,
sum( case when NC_FL='Yes' and CovB_inc_loss+CovB_alae >0 then 1 else 0 end) CovB_IC_ALAE_NC_FL ,
sum( case when NC_AO='Yes' and CovB_inc_loss+CovB_alae >0 then 1 else 0 end) CovB_IC_ALAE_NC_AO ,
sum( case when CAT_FL='Yes' and CovB_inc_loss+CovB_alae >0 then 1 else 0 end) CovB_IC_ALAE_Cat_Fire ,
sum( case when CAT_AO='Yes' and CovB_inc_loss+CovB_alae >0 then 1 else 0 end) CovB_IC_ALAE_Cat_AO ,
/*CovC*/
sum( case when NC_Water='Yes' and CovC_inc_loss + CovC_alae >0 then 1 else 0 end) CovC_IC_ALAE_NC_Water ,
sum( case when NC_WH='Yes' and CovC_inc_loss+CovC_alae >0 then 1 else 0 end) CovC_IC_ALAE_NC_WH ,
sum( case when NC_TV='Yes' and CovC_inc_loss+CovC_alae >0 then 1 else 0 end) CovC_IC_ALAE_NC_TV ,
sum( case when NC_FL='Yes' and CovC_inc_loss+CovC_alae >0 then 1 else 0 end) CovC_IC_ALAE_NC_FL ,
sum( case when NC_AO='Yes' and CovC_inc_loss+CovC_alae >0 then 1 else 0 end) CovC_IC_ALAE_NC_AO ,
sum( case when CAT_FL='Yes' and CovC_inc_loss+CovC_alae >0 then 1 else 0 end) CovC_IC_ALAE_Cat_Fire ,
sum( case when CAT_AO='Yes' and CovC_inc_loss+CovC_alae >0 then 1 else 0 end) CovC_IC_ALAE_Cat_AO ,
/*CovD*/
sum( case when NC_Water='Yes' and CovD_inc_loss + CovD_alae >0 then 1 else 0 end) CovD_IC_ALAE_NC_Water ,
sum( case when NC_WH='Yes' and CovD_inc_loss+CovD_alae >0 then 1 else 0 end) CovD_IC_ALAE_NC_WH ,
sum( case when NC_TV='Yes' and CovD_inc_loss+CovD_alae >0 then 1 else 0 end) CovD_IC_ALAE_NC_TV ,
sum( case when NC_FL='Yes' and CovD_inc_loss+CovD_alae >0 then 1 else 0 end) CovD_IC_ALAE_NC_FL ,
sum( case when NC_AO='Yes' and CovD_inc_loss+CovD_alae >0 then 1 else 0 end) CovD_IC_ALAE_NC_AO ,
sum( case when CAT_FL='Yes' and CovD_inc_loss+CovD_alae >0 then 1 else 0 end) CovD_IC_ALAE_Cat_Fire ,
sum( case when CAT_AO='Yes' and CovD_inc_loss+CovD_alae >0 then 1 else 0 end) CovD_IC_ALAE_Cat_AO ,
/*CovE*/
sum( case when NC_Water='Yes' and CovE_inc_loss + CovE_alae >0 then 1 else 0 end) CovE_IC_ALAE_NC_Water ,
sum( case when NC_WH='Yes' and CovE_inc_loss+CovE_alae >0 then 1 else 0 end) CovE_IC_ALAE_NC_WH ,
sum( case when NC_TV='Yes' and CovE_inc_loss+CovE_alae >0 then 1 else 0 end) CovE_IC_ALAE_NC_TV ,
sum( case when NC_FL='Yes' and CovE_inc_loss+CovE_alae >0 then 1 else 0 end) CovE_IC_ALAE_NC_FL ,
sum( case when NC_AO='Yes' and CovE_inc_loss+CovE_alae >0 then 1 else 0 end) CovE_IC_ALAE_NC_AO ,
sum( case when CAT_FL='Yes' and CovE_inc_loss+CovE_alae >0 then 1 else 0 end) CovE_IC_ALAE_Cat_Fire ,
sum( case when CAT_AO='Yes' and CovE_inc_loss+CovE_alae >0 then 1 else 0 end) CovE_IC_ALAE_Cat_AO ,
/*CovF*/
sum( case when NC_Water='Yes' and CovF_inc_loss + CovF_alae >0 then 1 else 0 end) CovF_IC_ALAE_NC_Water ,
sum( case when NC_WH='Yes' and CovF_inc_loss+CovF_alae >0 then 1 else 0 end) CovF_IC_ALAE_NC_WH ,
sum( case when NC_TV='Yes' and CovF_inc_loss+CovF_alae >0 then 1 else 0 end) CovF_IC_ALAE_NC_TV ,
sum( case when NC_FL='Yes' and CovF_inc_loss+CovF_alae >0 then 1 else 0 end) CovF_IC_ALAE_NC_FL ,
sum( case when NC_AO='Yes' and CovF_inc_loss+CovF_alae >0 then 1 else 0 end) CovF_IC_ALAE_NC_AO ,
sum( case when CAT_FL='Yes' and CovF_inc_loss+CovF_alae >0 then 1 else 0 end) CovF_IC_ALAE_Cat_Fire ,
sum( case when CAT_AO='Yes' and CovF_inc_loss+CovF_alae >0 then 1 else 0 end) CovF_IC_ALAE_Cat_AO ,
/*LIAB*/
sum( case when NC_Water='Yes' and LIAB_inc_loss + LIAB_alae >0 then 1 else 0 end) LIAB_IC_ALAE_NC_Water ,
sum( case when NC_WH='Yes' and LIAB_inc_loss+LIAB_alae >0 then 1 else 0 end) LIAB_IC_ALAE_NC_WH ,
sum( case when NC_TV='Yes' and LIAB_inc_loss+LIAB_alae >0 then 1 else 0 end) LIAB_IC_ALAE_NC_TV ,
sum( case when NC_FL='Yes' and LIAB_inc_loss+LIAB_alae >0 then 1 else 0 end) LIAB_IC_ALAE_NC_FL ,
sum( case when NC_AO='Yes' and LIAB_inc_loss+LIAB_alae >0 then 1 else 0 end) LIAB_IC_ALAE_NC_AO ,
sum( case when CAT_FL='Yes' and LIAB_inc_loss+LIAB_alae >0 then 1 else 0 end) LIAB_IC_ALAE_Cat_Fire ,
sum( case when CAT_AO='Yes' and LIAB_inc_loss+LIAB_alae >0 then 1 else 0 end) LIAB_IC_ALAE_Cat_AO
from fsbi_stg_spinn.STG_PROPERTY_MODELDATA stg
left outer join fsbi_stg_spinn.vstg_property_modeldata_claims c
on stg.claimrisk_id=c.claimrisk_id
group by
modeldata_id;
/*2. Final load into FACT table: 
staging + aggregated and grouped claim data + producer id 
*/
drop table if exists tmp_final;
create temporary table tmp_final as
select distinct
stg.modeldata_id ,
SystemIdStart ,
SystemIdEnd ,
stg.policy_id ,
stg.policy_uniqueid ,
dc.policy_changes_id ,
isnull(p.producer_id ,4) producer_id ,
Risk_id ,
Risk_uniqueid ,
RiskNumber ,
RiskType ,
Building_id ,
Building_uniqueid ,
StartDateTm ,
EndDateTm ,
startdate ,
enddate ,
CovA_deductible ,
CovB_deductible ,
CovC_deductible ,
CovD_deductible ,
CovE_deductible ,
CovF_deductible ,
CovA_Limit ,
CovB_Limit ,
CovC_Limit ,
CovD_Limit ,
CovE_Limit ,
CovF_Limit ,
OnPremises_Theft_Limit ,
AwayFromPremises_Theft_Limit,
CovA_FullTermAmt ,
CovB_FullTermAmt ,
CovC_FullTermAmt ,
CovD_FullTermAmt ,
CovE_FullTermAmt ,
CovF_FullTermAmt ,
Quality_PolAppInconsistency_Flg ,
Quality_RiskIdDuplicates_Flg ,
isnull( tmp_il.Quality_ClaimOk_Flg ,0) Quality_ClaimOk_Flg ,
isnull( tmp_il.Quality_ClaimPolicyTermJoin_Flg ,0) Quality_ClaimPolicyTermJoin_Flg ,
/*--*/
isnull( tmp_il.Loss ,0) Loss ,
isnull( tmp_il.Claim_Count ,0) Claim_Count ,
/*--*/
isnull( tmp_il.Cat_Loss ,0) Cat_Loss ,
isnull( tmp_il.Cat_Claim_Count ,0) Cat_Claim_Count ,
/*--*/
isnull( tmp_il.CovA_IL_NC_Water ,0) CovA_IL_NC_Water ,
isnull( tmp_il.CovA_IL_NC_WH ,0) CovA_IL_NC_WH ,
isnull( tmp_il.CovA_IL_NC_TV ,0) CovA_IL_NC_TV ,
isnull( tmp_il.CovA_IL_NC_FL ,0) CovA_IL_NC_FL ,
isnull( tmp_il.CovA_IL_NC_AO ,0) CovA_IL_NC_AO ,
isnull( tmp_il.CovA_IL_Cat_Fire ,0) CovA_IL_Cat_Fire ,
isnull( tmp_il.CovA_IL_Cat_AO ,0) CovA_IL_Cat_AO ,
/*--*/
isnull( tmp_il.CovB_IL_NC_Water ,0) CovB_IL_NC_Water ,
isnull( tmp_il.CovB_IL_NC_WH ,0) CovB_IL_NC_WH ,
isnull( tmp_il.CovB_IL_NC_TV ,0) CovB_IL_NC_TV ,
isnull( tmp_il.CovB_IL_NC_FL ,0) CovB_IL_NC_FL ,
isnull( tmp_il.CovB_IL_NC_AO ,0) CovB_IL_NC_AO ,
isnull( tmp_il.CovB_IL_Cat_Fire ,0) CovB_IL_Cat_Fire ,
isnull( tmp_il.CovB_IL_Cat_AO ,0) CovB_IL_Cat_AO ,
/*--*/
isnull( tmp_il.CovC_IL_NC_Water ,0) CovC_IL_NC_Water ,
isnull( tmp_il.CovC_IL_NC_WH ,0) CovC_IL_NC_WH ,
isnull( tmp_il.CovC_IL_NC_TV ,0) CovC_IL_NC_TV ,
isnull( tmp_il.CovC_IL_NC_FL ,0) CovC_IL_NC_FL ,
isnull( tmp_il.CovC_IL_NC_AO ,0) CovC_IL_NC_AO ,
isnull( tmp_il.CovC_IL_Cat_Fire ,0) CovC_IL_Cat_Fire ,
isnull( tmp_il.CovC_IL_Cat_AO ,0) CovC_IL_Cat_AO ,
/*--*/
isnull( tmp_il.CovD_IL_NC_Water ,0) CovD_IL_NC_Water ,
isnull( tmp_il.CovD_IL_NC_WH ,0) CovD_IL_NC_WH ,
isnull( tmp_il.CovD_IL_NC_TV ,0) CovD_IL_NC_TV ,
isnull( tmp_il.CovD_IL_NC_FL ,0) CovD_IL_NC_FL ,
isnull( tmp_il.CovD_IL_NC_AO ,0) CovD_IL_NC_AO ,
isnull( tmp_il.CovD_IL_Cat_Fire ,0) CovD_IL_Cat_Fire ,
isnull( tmp_il.CovD_IL_Cat_AO ,0) CovD_IL_Cat_AO ,
/*--*/
isnull( tmp_il.CovE_IL_NC_Water ,0) CovE_IL_NC_Water ,
isnull( tmp_il.CovE_IL_NC_WH ,0) CovE_IL_NC_WH ,
isnull( tmp_il.CovE_IL_NC_TV ,0) CovE_IL_NC_TV ,
isnull( tmp_il.CovE_IL_NC_FL ,0) CovE_IL_NC_FL ,
isnull( tmp_il.CovE_IL_NC_AO ,0) CovE_IL_NC_AO ,
isnull( tmp_il.CovE_IL_Cat_Fire ,0) CovE_IL_Cat_Fire ,
isnull( tmp_il.CovE_IL_Cat_AO ,0) CovE_IL_Cat_AO ,
/*--*/
isnull( tmp_il.CovF_IL_NC_Water ,0) CovF_IL_NC_Water ,
isnull( tmp_il.CovF_IL_NC_WH ,0) CovF_IL_NC_WH ,
isnull( tmp_il.CovF_IL_NC_TV ,0) CovF_IL_NC_TV ,
isnull( tmp_il.CovF_IL_NC_FL ,0) CovF_IL_NC_FL ,
isnull( tmp_il.CovF_IL_NC_AO ,0) CovF_IL_NC_AO ,
isnull( tmp_il.CovF_IL_Cat_Fire ,0) CovF_IL_Cat_Fire ,
isnull( tmp_il.CovF_IL_Cat_AO ,0) CovF_IL_Cat_AO ,
/*--*/
isnull( tmp_il.LIAB_IL_NC_Water ,0) LIAB_IL_NC_Water ,
isnull( tmp_il.LIAB_IL_NC_WH ,0) LIAB_IL_NC_WH ,
isnull( tmp_il.LIAB_IL_NC_TV ,0) LIAB_IL_NC_TV ,
isnull( tmp_il.LIAB_IL_NC_FL ,0) LIAB_IL_NC_FL ,
isnull( tmp_il.LIAB_IL_NC_AO ,0) LIAB_IL_NC_AO ,
isnull( tmp_il.LIAB_IL_Cat_Fire ,0) LIAB_IL_Cat_Fire ,
isnull( tmp_il.LIAB_IL_Cat_AO ,0) LIAB_IL_Cat_AO ,
/*--*/
isnull( tmp_il.CovA_IL_DCCE_NC_Water ,0) CovA_IL_DCCE_NC_Water ,
isnull( tmp_il.CovA_IL_DCCE_NC_WH ,0) CovA_IL_DCCE_NC_WH ,
isnull( tmp_il.CovA_IL_DCCE_NC_TV ,0) CovA_IL_DCCE_NC_TV ,
isnull( tmp_il.CovA_IL_DCCE_NC_FL ,0) CovA_IL_DCCE_NC_FL ,
isnull( tmp_il.CovA_IL_DCCE_NC_AO ,0) CovA_IL_DCCE_NC_AO ,
isnull( tmp_il.CovA_IL_DCCE_Cat_Fire ,0) CovA_IL_DCCE_Cat_Fire ,
isnull( tmp_il.CovA_IL_DCCE_Cat_AO ,0) CovA_IL_DCCE_Cat_AO ,
/*--*/
isnull( tmp_il.CovB_IL_DCCE_NC_Water ,0) CovB_IL_DCCE_NC_Water ,
isnull( tmp_il.CovB_IL_DCCE_NC_WH ,0) CovB_IL_DCCE_NC_WH ,
isnull( tmp_il.CovB_IL_DCCE_NC_TV ,0) CovB_IL_DCCE_NC_TV ,
isnull( tmp_il.CovB_IL_DCCE_NC_FL ,0) CovB_IL_DCCE_NC_FL ,
isnull( tmp_il.CovB_IL_DCCE_NC_AO ,0) CovB_IL_DCCE_NC_AO ,
isnull( tmp_il.CovB_IL_DCCE_Cat_Fire ,0) CovB_IL_DCCE_Cat_Fire ,
isnull( tmp_il.CovB_IL_DCCE_Cat_AO ,0) CovB_IL_DCCE_Cat_AO ,
/*--*/
isnull( tmp_il.CovC_IL_DCCE_NC_Water ,0) CovC_IL_DCCE_NC_Water ,
isnull( tmp_il.CovC_IL_DCCE_NC_WH ,0) CovC_IL_DCCE_NC_WH ,
isnull( tmp_il.CovC_IL_DCCE_NC_TV ,0) CovC_IL_DCCE_NC_TV ,
isnull( tmp_il.CovC_IL_DCCE_NC_FL ,0) CovC_IL_DCCE_NC_FL ,
isnull( tmp_il.CovC_IL_DCCE_NC_AO ,0) CovC_IL_DCCE_NC_AO ,
isnull( tmp_il.CovC_IL_DCCE_Cat_Fire ,0) CovC_IL_DCCE_Cat_Fire ,
isnull( tmp_il.CovC_IL_DCCE_Cat_AO ,0) CovC_IL_DCCE_Cat_AO ,
/*--*/
isnull( tmp_il.CovD_IL_DCCE_NC_Water ,0) CovD_IL_DCCE_NC_Water ,
isnull( tmp_il.CovD_IL_DCCE_NC_WH ,0) CovD_IL_DCCE_NC_WH ,
isnull( tmp_il.CovD_IL_DCCE_NC_TV ,0) CovD_IL_DCCE_NC_TV ,
isnull( tmp_il.CovD_IL_DCCE_NC_FL ,0) CovD_IL_DCCE_NC_FL ,
isnull( tmp_il.CovD_IL_DCCE_NC_AO ,0) CovD_IL_DCCE_NC_AO ,
isnull( tmp_il.CovD_IL_DCCE_Cat_Fire ,0) CovD_IL_DCCE_Cat_Fire ,
isnull( tmp_il.CovD_IL_DCCE_Cat_AO ,0) CovD_IL_DCCE_Cat_AO ,
/*--*/
isnull( tmp_il.CovE_IL_DCCE_NC_Water ,0) CovE_IL_DCCE_NC_Water ,
isnull( tmp_il.CovE_IL_DCCE_NC_WH ,0) CovE_IL_DCCE_NC_WH ,
isnull( tmp_il.CovE_IL_DCCE_NC_TV ,0) CovE_IL_DCCE_NC_TV ,
isnull( tmp_il.CovE_IL_DCCE_NC_FL ,0) CovE_IL_DCCE_NC_FL ,
isnull( tmp_il.CovE_IL_DCCE_NC_AO ,0) CovE_IL_DCCE_NC_AO ,
isnull( tmp_il.CovE_IL_DCCE_Cat_Fire ,0) CovE_IL_DCCE_Cat_Fire ,
isnull( tmp_il.CovE_IL_DCCE_Cat_AO ,0) CovE_IL_DCCE_Cat_AO ,
/*--*/
isnull( tmp_il.CovF_IL_DCCE_NC_Water ,0) CovF_IL_DCCE_NC_Water ,
isnull( tmp_il.CovF_IL_DCCE_NC_WH ,0) CovF_IL_DCCE_NC_WH ,
isnull( tmp_il.CovF_IL_DCCE_NC_TV ,0) CovF_IL_DCCE_NC_TV ,
isnull( tmp_il.CovF_IL_DCCE_NC_FL ,0) CovF_IL_DCCE_NC_FL ,
isnull( tmp_il.CovF_IL_DCCE_NC_AO ,0) CovF_IL_DCCE_NC_AO ,
isnull( tmp_il.CovF_IL_DCCE_Cat_Fire ,0) CovF_IL_DCCE_Cat_Fire ,
isnull( tmp_il.CovF_IL_DCCE_Cat_AO ,0) CovF_IL_DCCE_Cat_AO ,
/*--*/
isnull( tmp_il.LIAB_IL_DCCE_NC_Water ,0) LIAB_IL_DCCE_NC_Water ,
isnull( tmp_il.LIAB_IL_DCCE_NC_WH ,0) LIAB_IL_DCCE_NC_WH ,
isnull( tmp_il.LIAB_IL_DCCE_NC_TV ,0) LIAB_IL_DCCE_NC_TV ,
isnull( tmp_il.LIAB_IL_DCCE_NC_FL ,0) LIAB_IL_DCCE_NC_FL ,
isnull( tmp_il.LIAB_IL_DCCE_NC_AO ,0) LIAB_IL_DCCE_NC_AO ,
isnull( tmp_il.LIAB_IL_DCCE_Cat_Fire ,0) LIAB_IL_DCCE_Cat_Fire ,
isnull( tmp_il.LIAB_IL_DCCE_Cat_AO ,0) LIAB_IL_DCCE_Cat_AO ,
/*--*/
isnull( tmp_il.CovA_IL_ALAE_NC_Water ,0) CovA_IL_ALAE_NC_Water ,
isnull( tmp_il.CovA_IL_ALAE_NC_WH ,0) CovA_IL_ALAE_NC_WH ,
isnull( tmp_il.CovA_IL_ALAE_NC_TV ,0) CovA_IL_ALAE_NC_TV ,
isnull( tmp_il.CovA_IL_ALAE_NC_FL ,0) CovA_IL_ALAE_NC_FL ,
isnull( tmp_il.CovA_IL_ALAE_NC_AO ,0) CovA_IL_ALAE_NC_AO ,
isnull( tmp_il.CovA_IL_ALAE_Cat_Fire ,0) CovA_IL_ALAE_Cat_Fire ,
isnull( tmp_il.CovA_IL_ALAE_Cat_AO ,0) CovA_IL_ALAE_Cat_AO ,
/*--*/
isnull( tmp_il.CovB_IL_ALAE_NC_Water ,0) CovB_IL_ALAE_NC_Water ,
isnull( tmp_il.CovB_IL_ALAE_NC_WH ,0) CovB_IL_ALAE_NC_WH ,
isnull( tmp_il.CovB_IL_ALAE_NC_TV ,0) CovB_IL_ALAE_NC_TV ,
isnull( tmp_il.CovB_IL_ALAE_NC_FL ,0) CovB_IL_ALAE_NC_FL ,
isnull( tmp_il.CovB_IL_ALAE_NC_AO ,0) CovB_IL_ALAE_NC_AO ,
isnull( tmp_il.CovB_IL_ALAE_Cat_Fire ,0) CovB_IL_ALAE_Cat_Fire ,
isnull( tmp_il.CovB_IL_ALAE_Cat_AO ,0) CovB_IL_ALAE_Cat_AO ,
/*--*/
isnull( tmp_il.CovC_IL_ALAE_NC_Water ,0) CovC_IL_ALAE_NC_Water ,
isnull( tmp_il.CovC_IL_ALAE_NC_WH ,0) CovC_IL_ALAE_NC_WH ,
isnull( tmp_il.CovC_IL_ALAE_NC_TV ,0) CovC_IL_ALAE_NC_TV ,
isnull( tmp_il.CovC_IL_ALAE_NC_FL ,0) CovC_IL_ALAE_NC_FL ,
isnull( tmp_il.CovC_IL_ALAE_NC_AO ,0) CovC_IL_ALAE_NC_AO ,
isnull( tmp_il.CovC_IL_ALAE_Cat_Fire ,0) CovC_IL_ALAE_Cat_Fire ,
isnull( tmp_il.CovC_IL_ALAE_Cat_AO ,0) CovC_IL_ALAE_Cat_AO ,
/*--*/
isnull( tmp_il.CovD_IL_ALAE_NC_Water ,0) CovD_IL_ALAE_NC_Water ,
isnull( tmp_il.CovD_IL_ALAE_NC_WH ,0) CovD_IL_ALAE_NC_WH ,
isnull( tmp_il.CovD_IL_ALAE_NC_TV ,0) CovD_IL_ALAE_NC_TV ,
isnull( tmp_il.CovD_IL_ALAE_NC_FL ,0) CovD_IL_ALAE_NC_FL ,
isnull( tmp_il.CovD_IL_ALAE_NC_AO ,0) CovD_IL_ALAE_NC_AO ,
isnull( tmp_il.CovD_IL_ALAE_Cat_Fire ,0) CovD_IL_ALAE_Cat_Fire ,
isnull( tmp_il.CovD_IL_ALAE_Cat_AO ,0) CovD_IL_ALAE_Cat_AO ,
/*--*/
isnull( tmp_il.CovE_IL_ALAE_NC_Water ,0) CovE_IL_ALAE_NC_Water ,
isnull( tmp_il.CovE_IL_ALAE_NC_WH ,0) CovE_IL_ALAE_NC_WH ,
isnull( tmp_il.CovE_IL_ALAE_NC_TV ,0) CovE_IL_ALAE_NC_TV ,
isnull( tmp_il.CovE_IL_ALAE_NC_FL ,0) CovE_IL_ALAE_NC_FL ,
isnull( tmp_il.CovE_IL_ALAE_NC_AO ,0) CovE_IL_ALAE_NC_AO ,
isnull( tmp_il.CovE_IL_ALAE_Cat_Fire ,0) CovE_IL_ALAE_Cat_Fire ,
isnull( tmp_il.CovE_IL_ALAE_Cat_AO ,0) CovE_IL_ALAE_Cat_AO ,
/*--*/
isnull( tmp_il.CovF_IL_ALAE_NC_Water ,0) CovF_IL_ALAE_NC_Water ,
isnull( tmp_il.CovF_IL_ALAE_NC_WH ,0) CovF_IL_ALAE_NC_WH ,
isnull( tmp_il.CovF_IL_ALAE_NC_TV ,0) CovF_IL_ALAE_NC_TV ,
isnull( tmp_il.CovF_IL_ALAE_NC_FL ,0) CovF_IL_ALAE_NC_FL ,
isnull( tmp_il.CovF_IL_ALAE_NC_AO ,0) CovF_IL_ALAE_NC_AO ,
isnull( tmp_il.CovF_IL_ALAE_Cat_Fire ,0) CovF_IL_ALAE_Cat_Fire ,
isnull( tmp_il.CovF_IL_ALAE_Cat_AO ,0) CovF_IL_ALAE_Cat_AO ,
/*--*/
isnull( tmp_il.LIAB_IL_ALAE_NC_Water ,0) LIAB_IL_ALAE_NC_Water ,
isnull( tmp_il.LIAB_IL_ALAE_NC_WH ,0) LIAB_IL_ALAE_NC_WH ,
isnull( tmp_il.LIAB_IL_ALAE_NC_TV ,0) LIAB_IL_ALAE_NC_TV ,
isnull( tmp_il.LIAB_IL_ALAE_NC_FL ,0) LIAB_IL_ALAE_NC_FL ,
isnull( tmp_il.LIAB_IL_ALAE_NC_AO ,0) LIAB_IL_ALAE_NC_AO ,
isnull( tmp_il.LIAB_IL_ALAE_Cat_Fire ,0) LIAB_IL_ALAE_Cat_Fire ,
isnull( tmp_il.LIAB_IL_ALAE_Cat_AO ,0) LIAB_IL_ALAE_Cat_AO ,
isnull( tmp_il.AllCov_LossInc ,0) AllCov_LossInc ,
isnull( tmp_il.AllCov_LossDCCE ,0) AllCov_LossDCCE ,
isnull( tmp_il.AllCov_LossALAE ,0) AllCov_LossALAE ,
/*==========*/
isnull( tmp_ic.CovA_IC_NC_Water ,0) CovA_IC_NC_Water ,
isnull( tmp_ic.CovA_IC_NC_WH ,0) CovA_IC_NC_WH ,
isnull( tmp_ic.CovA_IC_NC_TV ,0) CovA_IC_NC_TV ,
isnull( tmp_ic.CovA_IC_NC_FL ,0) CovA_IC_NC_FL ,
isnull( tmp_ic.CovA_IC_NC_AO ,0) CovA_IC_NC_AO ,
isnull( tmp_ic.CovA_IC_Cat_Fire ,0) CovA_IC_Cat_Fire ,
isnull( tmp_ic.CovA_IC_Cat_AO ,0) CovA_IC_Cat_AO ,
/*--*/
isnull( tmp_ic.CovB_IC_NC_Water ,0) CovB_IC_NC_Water ,
isnull( tmp_ic.CovB_IC_NC_WH ,0) CovB_IC_NC_WH ,
isnull( tmp_ic.CovB_IC_NC_TV ,0) CovB_IC_NC_TV ,
isnull( tmp_ic.CovB_IC_NC_FL ,0) CovB_IC_NC_FL ,
isnull( tmp_ic.CovB_IC_NC_AO ,0) CovB_IC_NC_AO ,
isnull( tmp_ic.CovB_IC_Cat_Fire ,0) CovB_IC_Cat_Fire ,
isnull( tmp_ic.CovB_IC_Cat_AO ,0) CovB_IC_Cat_AO ,
/*--*/
isnull( tmp_ic.CovC_IC_NC_Water ,0) CovC_IC_NC_Water ,
isnull( tmp_ic.CovC_IC_NC_WH ,0) CovC_IC_NC_WH ,
isnull( tmp_ic.CovC_IC_NC_TV ,0) CovC_IC_NC_TV ,
isnull( tmp_ic.CovC_IC_NC_FL ,0) CovC_IC_NC_FL ,
isnull( tmp_ic.CovC_IC_NC_AO ,0) CovC_IC_NC_AO ,
isnull( tmp_ic.CovC_IC_Cat_Fire ,0) CovC_IC_Cat_Fire ,
isnull( tmp_ic.CovC_IC_Cat_AO ,0) CovC_IC_Cat_AO ,
/*--*/
isnull( tmp_ic.CovD_IC_NC_Water ,0) CovD_IC_NC_Water ,
isnull( tmp_ic.CovD_IC_NC_WH ,0) CovD_IC_NC_WH ,
isnull( tmp_ic.CovD_IC_NC_TV ,0) CovD_IC_NC_TV ,
isnull( tmp_ic.CovD_IC_NC_FL ,0) CovD_IC_NC_FL ,
isnull( tmp_ic.CovD_IC_NC_AO ,0) CovD_IC_NC_AO ,
isnull( tmp_ic.CovD_IC_Cat_Fire ,0) CovD_IC_Cat_Fire ,
isnull( tmp_ic.CovD_IC_Cat_AO ,0) CovD_IC_Cat_AO ,
/*--*/
isnull( tmp_ic.CovE_IC_NC_Water ,0) CovE_IC_NC_Water ,
isnull( tmp_ic.CovE_IC_NC_WH ,0) CovE_IC_NC_WH ,
isnull( tmp_ic.CovE_IC_NC_TV ,0) CovE_IC_NC_TV ,
isnull( tmp_ic.CovE_IC_NC_FL ,0) CovE_IC_NC_FL ,
isnull( tmp_ic.CovE_IC_NC_AO ,0) CovE_IC_NC_AO ,
isnull( tmp_ic.CovE_IC_Cat_Fire ,0) CovE_IC_Cat_Fire ,
isnull( tmp_ic.CovE_IC_Cat_AO ,0) CovE_IC_Cat_AO ,
/*--*/
isnull( tmp_ic.CovF_IC_NC_Water ,0) CovF_IC_NC_Water ,
isnull( tmp_ic.CovF_IC_NC_WH ,0) CovF_IC_NC_WH ,
isnull( tmp_ic.CovF_IC_NC_TV ,0) CovF_IC_NC_TV ,
isnull( tmp_ic.CovF_IC_NC_FL ,0) CovF_IC_NC_FL ,
isnull( tmp_ic.CovF_IC_NC_AO ,0) CovF_IC_NC_AO ,
isnull( tmp_ic.CovF_IC_Cat_Fire ,0) CovF_IC_Cat_Fire ,
isnull( tmp_ic.CovF_IC_Cat_AO ,0) CovF_IC_Cat_AO ,
/*--*/
isnull( tmp_ic.LIAB_IC_NC_Water ,0) LIAB_IC_NC_Water ,
isnull( tmp_ic.LIAB_IC_NC_WH ,0) LIAB_IC_NC_WH ,
isnull( tmp_ic.LIAB_IC_NC_TV ,0) LIAB_IC_NC_TV ,
isnull( tmp_ic.LIAB_IC_NC_FL ,0) LIAB_IC_NC_FL ,
isnull( tmp_ic.LIAB_IC_NC_AO ,0) LIAB_IC_NC_AO ,
isnull( tmp_ic.LIAB_IC_Cat_Fire ,0) LIAB_IC_Cat_Fire ,
isnull( tmp_ic.LIAB_IC_Cat_AO ,0) LIAB_IC_Cat_AO ,
/*--*/
isnull( tmp_ic.CovA_IC_DCCE_NC_Water ,0) CovA_IC_DCCE_NC_Water ,
isnull( tmp_ic.CovA_IC_DCCE_NC_WH ,0) CovA_IC_DCCE_NC_WH ,
isnull( tmp_ic.CovA_IC_DCCE_NC_TV ,0) CovA_IC_DCCE_NC_TV ,
isnull( tmp_ic.CovA_IC_DCCE_NC_FL ,0) CovA_IC_DCCE_NC_FL ,
isnull( tmp_ic.CovA_IC_DCCE_NC_AO ,0) CovA_IC_DCCE_NC_AO ,
isnull( tmp_ic.CovA_IC_DCCE_Cat_Fire ,0) CovA_IC_DCCE_Cat_Fire ,
isnull( tmp_ic.CovA_IC_DCCE_Cat_AO ,0) CovA_IC_DCCE_Cat_AO ,
/*--*/
isnull( tmp_ic.CovB_IC_DCCE_NC_Water ,0) CovB_IC_DCCE_NC_Water ,
isnull( tmp_ic.CovB_IC_DCCE_NC_WH ,0) CovB_IC_DCCE_NC_WH ,
isnull( tmp_ic.CovB_IC_DCCE_NC_TV ,0) CovB_IC_DCCE_NC_TV ,
isnull( tmp_ic.CovB_IC_DCCE_NC_FL ,0) CovB_IC_DCCE_NC_FL ,
isnull( tmp_ic.CovB_IC_DCCE_NC_AO ,0) CovB_IC_DCCE_NC_AO ,
isnull( tmp_ic.CovB_IC_DCCE_Cat_Fire ,0) CovB_IC_DCCE_Cat_Fire ,
isnull( tmp_ic.CovB_IC_DCCE_Cat_AO ,0) CovB_IC_DCCE_Cat_AO ,
/*--*/
isnull( tmp_ic.CovC_IC_DCCE_NC_Water ,0) CovC_IC_DCCE_NC_Water ,
isnull( tmp_ic.CovC_IC_DCCE_NC_WH ,0) CovC_IC_DCCE_NC_WH ,
isnull( tmp_ic.CovC_IC_DCCE_NC_TV ,0) CovC_IC_DCCE_NC_TV ,
isnull( tmp_ic.CovC_IC_DCCE_NC_FL ,0) CovC_IC_DCCE_NC_FL ,
isnull( tmp_ic.CovC_IC_DCCE_NC_AO ,0) CovC_IC_DCCE_NC_AO ,
isnull( tmp_ic.CovC_IC_DCCE_Cat_Fire ,0) CovC_IC_DCCE_Cat_Fire ,
isnull( tmp_ic.CovC_IC_DCCE_Cat_AO ,0) CovC_IC_DCCE_Cat_AO ,
/*--*/
isnull( tmp_ic.CovD_IC_DCCE_NC_Water ,0) CovD_IC_DCCE_NC_Water ,
isnull( tmp_ic.CovD_IC_DCCE_NC_WH ,0) CovD_IC_DCCE_NC_WH ,
isnull( tmp_ic.CovD_IC_DCCE_NC_TV ,0) CovD_IC_DCCE_NC_TV ,
isnull( tmp_ic.CovD_IC_DCCE_NC_FL ,0) CovD_IC_DCCE_NC_FL ,
isnull( tmp_ic.CovD_IC_DCCE_NC_AO ,0) CovD_IC_DCCE_NC_AO ,
isnull( tmp_ic.CovD_IC_DCCE_Cat_Fire ,0) CovD_IC_DCCE_Cat_Fire ,
isnull( tmp_ic.CovD_IC_DCCE_Cat_AO ,0) CovD_IC_DCCE_Cat_AO ,
/*--*/
isnull( tmp_ic.CovE_IC_DCCE_NC_Water ,0) CovE_IC_DCCE_NC_Water ,
isnull( tmp_ic.CovE_IC_DCCE_NC_WH ,0) CovE_IC_DCCE_NC_WH ,
isnull( tmp_ic.CovE_IC_DCCE_NC_TV ,0) CovE_IC_DCCE_NC_TV ,
isnull( tmp_ic.CovE_IC_DCCE_NC_FL ,0) CovE_IC_DCCE_NC_FL ,
isnull( tmp_ic.CovE_IC_DCCE_NC_AO ,0) CovE_IC_DCCE_NC_AO ,
isnull( tmp_ic.CovE_IC_DCCE_Cat_Fire ,0) CovE_IC_DCCE_Cat_Fire ,
isnull( tmp_ic.CovE_IC_DCCE_Cat_AO ,0) CovE_IC_DCCE_Cat_AO ,
/*--*/
isnull( tmp_ic.CovF_IC_DCCE_NC_Water ,0) CovF_IC_DCCE_NC_Water ,
isnull( tmp_ic.CovF_IC_DCCE_NC_WH ,0) CovF_IC_DCCE_NC_WH ,
isnull( tmp_ic.CovF_IC_DCCE_NC_TV ,0) CovF_IC_DCCE_NC_TV ,
isnull( tmp_ic.CovF_IC_DCCE_NC_FL ,0) CovF_IC_DCCE_NC_FL ,
isnull( tmp_ic.CovF_IC_DCCE_NC_AO ,0) CovF_IC_DCCE_NC_AO ,
isnull( tmp_ic.CovF_IC_DCCE_Cat_Fire ,0) CovF_IC_DCCE_Cat_Fire ,
isnull( tmp_ic.CovF_IC_DCCE_Cat_AO ,0) CovF_IC_DCCE_Cat_AO ,
/*--*/
isnull( tmp_ic.LIAB_IC_DCCE_NC_Water ,0) LIAB_IC_DCCE_NC_Water ,
isnull( tmp_ic.LIAB_IC_DCCE_NC_WH ,0) LIAB_IC_DCCE_NC_WH ,
isnull( tmp_ic.LIAB_IC_DCCE_NC_TV ,0) LIAB_IC_DCCE_NC_TV ,
isnull( tmp_ic.LIAB_IC_DCCE_NC_FL ,0) LIAB_IC_DCCE_NC_FL ,
isnull( tmp_ic.LIAB_IC_DCCE_NC_AO ,0) LIAB_IC_DCCE_NC_AO ,
isnull( tmp_ic.LIAB_IC_DCCE_Cat_Fire ,0) LIAB_IC_DCCE_Cat_Fire ,
isnull( tmp_ic.LIAB_IC_DCCE_Cat_AO ,0) LIAB_IC_DCCE_Cat_AO ,
/*--*/
isnull( tmp_ic.CovA_IC_ALAE_NC_Water ,0) CovA_IC_ALAE_NC_Water ,
isnull( tmp_ic.CovA_IC_ALAE_NC_WH ,0) CovA_IC_ALAE_NC_WH ,
isnull( tmp_ic.CovA_IC_ALAE_NC_TV ,0) CovA_IC_ALAE_NC_TV ,
isnull( tmp_ic.CovA_IC_ALAE_NC_FL ,0) CovA_IC_ALAE_NC_FL ,
isnull( tmp_ic.CovA_IC_ALAE_NC_AO ,0) CovA_IC_ALAE_NC_AO ,
isnull( tmp_ic.CovA_IC_ALAE_Cat_Fire ,0) CovA_IC_ALAE_Cat_Fire ,
isnull( tmp_ic.CovA_IC_ALAE_Cat_AO ,0) CovA_IC_ALAE_Cat_AO ,
/*--*/
isnull( tmp_ic.CovB_IC_ALAE_NC_Water ,0) CovB_IC_ALAE_NC_Water ,
isnull( tmp_ic.CovB_IC_ALAE_NC_WH ,0) CovB_IC_ALAE_NC_WH ,
isnull( tmp_ic.CovB_IC_ALAE_NC_TV ,0) CovB_IC_ALAE_NC_TV ,
isnull( tmp_ic.CovB_IC_ALAE_NC_FL ,0) CovB_IC_ALAE_NC_FL ,
isnull( tmp_ic.CovB_IC_ALAE_NC_AO ,0) CovB_IC_ALAE_NC_AO ,
isnull( tmp_ic.CovB_IC_ALAE_Cat_Fire ,0) CovB_IC_ALAE_Cat_Fire ,
isnull( tmp_ic.CovB_IC_ALAE_Cat_AO ,0) CovB_IC_ALAE_Cat_AO ,
/*--*/
isnull( tmp_ic.CovC_IC_ALAE_NC_Water ,0) CovC_IC_ALAE_NC_Water ,
isnull( tmp_ic.CovC_IC_ALAE_NC_WH ,0) CovC_IC_ALAE_NC_WH ,
isnull( tmp_ic.CovC_IC_ALAE_NC_TV ,0) CovC_IC_ALAE_NC_TV ,
isnull( tmp_ic.CovC_IC_ALAE_NC_FL ,0) CovC_IC_ALAE_NC_FL ,
isnull( tmp_ic.CovC_IC_ALAE_NC_AO ,0) CovC_IC_ALAE_NC_AO ,
isnull( tmp_ic.CovC_IC_ALAE_Cat_Fire ,0) CovC_IC_ALAE_Cat_Fire ,
isnull( tmp_ic.CovC_IC_ALAE_Cat_AO ,0) CovC_IC_ALAE_Cat_AO ,
/*--*/
isnull( tmp_ic.CovD_IC_ALAE_NC_Water ,0) CovD_IC_ALAE_NC_Water ,
isnull( tmp_ic.CovD_IC_ALAE_NC_WH ,0) CovD_IC_ALAE_NC_WH ,
isnull( tmp_ic.CovD_IC_ALAE_NC_TV ,0) CovD_IC_ALAE_NC_TV ,
isnull( tmp_ic.CovD_IC_ALAE_NC_FL ,0) CovD_IC_ALAE_NC_FL ,
isnull( tmp_ic.CovD_IC_ALAE_NC_AO ,0) CovD_IC_ALAE_NC_AO ,
isnull( tmp_ic.CovD_IC_ALAE_Cat_Fire ,0) CovD_IC_ALAE_Cat_Fire ,
isnull( tmp_ic.CovD_IC_ALAE_Cat_AO ,0) CovD_IC_ALAE_Cat_AO ,
/*--*/
isnull( tmp_ic.CovE_IC_ALAE_NC_Water ,0) CovE_IC_ALAE_NC_Water ,
isnull( tmp_ic.CovE_IC_ALAE_NC_WH ,0) CovE_IC_ALAE_NC_WH ,
isnull( tmp_ic.CovE_IC_ALAE_NC_TV ,0) CovE_IC_ALAE_NC_TV ,
isnull( tmp_ic.CovE_IC_ALAE_NC_FL ,0) CovE_IC_ALAE_NC_FL ,
isnull( tmp_ic.CovE_IC_ALAE_NC_AO ,0) CovE_IC_ALAE_NC_AO ,
isnull( tmp_ic.CovE_IC_ALAE_Cat_Fire ,0) CovE_IC_ALAE_Cat_Fire ,
isnull( tmp_ic.CovE_IC_ALAE_Cat_AO ,0) CovE_IC_ALAE_Cat_AO ,
/*--*/
isnull( tmp_ic.CovF_IC_ALAE_NC_Water ,0) CovF_IC_ALAE_NC_Water ,
isnull( tmp_ic.CovF_IC_ALAE_NC_WH ,0) CovF_IC_ALAE_NC_WH ,
isnull( tmp_ic.CovF_IC_ALAE_NC_TV ,0) CovF_IC_ALAE_NC_TV ,
isnull( tmp_ic.CovF_IC_ALAE_NC_FL ,0) CovF_IC_ALAE_NC_FL ,
isnull( tmp_ic.CovF_IC_ALAE_NC_AO ,0) CovF_IC_ALAE_NC_AO ,
isnull( tmp_ic.CovF_IC_ALAE_Cat_Fire ,0) CovF_IC_ALAE_Cat_Fire ,
isnull( tmp_ic.CovF_IC_ALAE_Cat_AO ,0) CovF_IC_ALAE_Cat_AO ,
/*--*/
isnull( tmp_ic.LIAB_IC_ALAE_NC_Water ,0) LIAB_IC_ALAE_NC_Water ,
isnull( tmp_ic.LIAB_IC_ALAE_NC_WH ,0) LIAB_IC_ALAE_NC_WH ,
isnull( tmp_ic.LIAB_IC_ALAE_NC_TV ,0) LIAB_IC_ALAE_NC_TV ,
isnull( tmp_ic.LIAB_IC_ALAE_NC_FL ,0) LIAB_IC_ALAE_NC_FL ,
isnull( tmp_ic.LIAB_IC_ALAE_NC_AO ,0) LIAB_IC_ALAE_NC_AO ,
isnull( tmp_ic.LIAB_IC_ALAE_Cat_Fire ,0) LIAB_IC_ALAE_Cat_Fire ,
isnull( tmp_ic.LIAB_IC_ALAE_Cat_AO ,0) LIAB_IC_ALAE_Cat_AO ,
/*--*/
isnull( CovA_FL ,0) CovA_FL ,
isnull( CovA_SF ,0) CovA_SF ,
isnull( CovA_EC ,0) CovA_EC ,
isnull( CovC_FL ,0) CovC_FL ,
isnull( CovC_SF ,0) CovC_SF ,
isnull( CovC_EC ,0) CovC_EC ,
/*--*/
GetDate() LoadDate
from fsbi_stg_spinn.STG_PROPERTY_MODELDATA stg
left outer join tmp_FACT_HO_LL_MODELDATA_IL tmp_il
on stg.modeldata_id=tmp_il.modeldata_id
left outer join tmp_FACT_HO_LL_MODELDATA_IC tmp_ic
on stg.modeldata_id=tmp_ic.modeldata_id
left outer join fsbi_dw_spinn.DIM_PRODUCER p
on p.producer_uniqueid=isnull(stg.producer_uniqueid,'Unknown')
and stg.Startdatetm >= p.valid_fromdate and stg.Startdatetm<p.valid_todate
join fsbi_dw_spinn.DIM_POLICY_CHANGES dc
on stg.policy_uniqueid=dc.policy_uniqueid
and stg.Startdatetm >= dc.valid_fromdate and stg.Startdatetm<dc.valid_todate;
drop table if exists tmp_FACT_HO_LL_MODELDATA_IL;
drop table if exists tmp_FACT_HO_LL_MODELDATA_IC;
/*3. FullTermAmt (WP) per policy_uniqueid, systemid , risk_id and all coverages 
*/
drop table if exists tmp_all_wp;
create temporary table tmp_all_wp as
select
policy_uniqueid,
systemid,
risk_uniqueid,
sum(FullTermAmt) WP
from fsbi_stg_spinn.vstg_property_modeldata_coverage cov
group by
policy_uniqueid,
systemid,
risk_uniqueid ;
truncate table fsbi_dw_spinn.FACT_PROPERTY_MODELDATA;
insert into fsbi_dw_spinn.FACT_PROPERTY_MODELDATA
select distinct
modeldata_id ,
SystemIdStart ,
SystemIdEnd ,
policy_id ,
f.policy_uniqueid ,
policy_changes_id ,
producer_id ,
f.Risk_id ,
f.Risk_uniqueid ,
RiskNumber ,
RiskType ,
Building_id ,
Building_uniqueid ,
StartDateTm ,
EndDateTm ,
startdate,
enddate,
isnull(WP.WP,0) AllCov_WP,
AllCov_LossInc,
AllCov_LossDCCE,
AllCov_LossALAE,
isnull(CovA_FullTermAmt ,0) CovA_wp,
isnull(CovB_FullTermAmt ,0) CovB_wp,
isnull(CovC_FullTermAmt ,0) CovC_wp,
isnull(CovD_FullTermAmt ,0) CovD_wp,
isnull(CovE_FullTermAmt ,0) CovE_wp,
isnull(CovF_FullTermAmt ,0) CovF_wp,
CovA_deductible ,
CovB_deductible ,
CovC_deductible ,
CovD_deductible ,
CovE_deductible ,
CovF_deductible ,
CovA_Limit ,
CovB_Limit ,
CovC_Limit ,
CovD_Limit ,
CovE_Limit ,
CovF_Limit ,
OnPremises_Theft_Limit ,
AwayFromPremises_Theft_Limit,
Quality_PolAppInconsistency_Flg ,
Quality_RiskIdDuplicates_Flg ,
Quality_ClaimOk_Flg ,
Quality_ClaimPolicyTermJoin_Flg ,
Loss ,
Claim_Count ,
Cat_Loss ,
Cat_Claim_Count ,
CovA_IL_NC_Water ,
CovA_IL_NC_WH ,
CovA_IL_NC_TV ,
CovA_IL_NC_FL ,
CovA_IL_NC_AO ,
CovA_IL_Cat_Fire ,
CovA_IL_Cat_AO ,
CovB_IL_NC_Water ,
CovB_IL_NC_WH ,
CovB_IL_NC_TV ,
CovB_IL_NC_FL ,
CovB_IL_NC_AO ,
CovB_IL_Cat_Fire ,
CovB_IL_Cat_AO ,
CovC_IL_NC_Water ,
CovC_IL_NC_WH ,
CovC_IL_NC_TV ,
CovC_IL_NC_FL ,
CovC_IL_NC_AO ,
CovC_IL_Cat_Fire ,
CovC_IL_Cat_AO ,
CovD_IL_NC_Water ,
CovD_IL_NC_WH ,
CovD_IL_NC_TV ,
CovD_IL_NC_FL ,
CovD_IL_NC_AO ,
CovD_IL_Cat_Fire ,
CovD_IL_Cat_AO ,
CovE_IL_NC_Water ,
CovE_IL_NC_WH ,
CovE_IL_NC_TV ,
CovE_IL_NC_FL ,
CovE_IL_NC_AO ,
CovE_IL_Cat_Fire ,
CovE_IL_Cat_AO ,
CovF_IL_NC_Water ,
CovF_IL_NC_WH ,
CovF_IL_NC_TV ,
CovF_IL_NC_FL ,
CovF_IL_NC_AO ,
CovF_IL_Cat_Fire ,
CovF_IL_Cat_AO ,
LIAB_IL_NC_Water ,
LIAB_IL_NC_WH ,
LIAB_IL_NC_TV ,
LIAB_IL_NC_FL ,
LIAB_IL_NC_AO ,
LIAB_IL_Cat_Fire ,
LIAB_IL_Cat_AO ,
CovA_IL_DCCE_NC_Water ,
CovA_IL_DCCE_NC_WH ,
CovA_IL_DCCE_NC_TV ,
CovA_IL_DCCE_NC_FL ,
CovA_IL_DCCE_NC_AO ,
CovA_IL_DCCE_Cat_Fire ,
CovA_IL_DCCE_Cat_AO ,
CovB_IL_DCCE_NC_Water ,
CovB_IL_DCCE_NC_WH ,
CovB_IL_DCCE_NC_TV ,
CovB_IL_DCCE_NC_FL ,
CovB_IL_DCCE_NC_AO ,
CovB_IL_DCCE_Cat_Fire ,
CovB_IL_DCCE_Cat_AO ,
CovC_IL_DCCE_NC_Water ,
CovC_IL_DCCE_NC_WH ,
CovC_IL_DCCE_NC_TV ,
CovC_IL_DCCE_NC_FL ,
CovC_IL_DCCE_NC_AO ,
CovC_IL_DCCE_Cat_Fire ,
CovC_IL_DCCE_Cat_AO ,
CovD_IL_DCCE_NC_Water ,
CovD_IL_DCCE_NC_WH ,
CovD_IL_DCCE_NC_TV ,
CovD_IL_DCCE_NC_FL ,
CovD_IL_DCCE_NC_AO ,
CovD_IL_DCCE_Cat_Fire ,
CovD_IL_DCCE_Cat_AO ,
CovE_IL_DCCE_NC_Water ,
CovE_IL_DCCE_NC_WH ,
CovE_IL_DCCE_NC_TV ,
CovE_IL_DCCE_NC_FL ,
CovE_IL_DCCE_NC_AO ,
CovE_IL_DCCE_Cat_Fire ,
CovE_IL_DCCE_Cat_AO ,
CovF_IL_DCCE_NC_Water ,
CovF_IL_DCCE_NC_WH ,
CovF_IL_DCCE_NC_TV ,
CovF_IL_DCCE_NC_FL ,
CovF_IL_DCCE_NC_AO ,
CovF_IL_DCCE_Cat_Fire ,
CovF_IL_DCCE_Cat_AO ,
LIAB_IL_DCCE_NC_Water ,
LIAB_IL_DCCE_NC_WH ,
LIAB_IL_DCCE_NC_TV ,
LIAB_IL_DCCE_NC_FL ,
LIAB_IL_DCCE_NC_AO ,
LIAB_IL_DCCE_Cat_Fire ,
LIAB_IL_DCCE_Cat_AO ,
CovA_IL_ALAE_NC_Water ,
CovA_IL_ALAE_NC_WH ,
CovA_IL_ALAE_NC_TV ,
CovA_IL_ALAE_NC_FL ,
CovA_IL_ALAE_NC_AO ,
CovA_IL_ALAE_Cat_Fire ,
CovA_IL_ALAE_Cat_AO ,
CovB_IL_ALAE_NC_Water ,
CovB_IL_ALAE_NC_WH ,
CovB_IL_ALAE_NC_TV ,
CovB_IL_ALAE_NC_FL ,
CovB_IL_ALAE_NC_AO ,
CovB_IL_ALAE_Cat_Fire ,
CovB_IL_ALAE_Cat_AO ,
CovC_IL_ALAE_NC_Water ,
CovC_IL_ALAE_NC_WH ,
CovC_IL_ALAE_NC_TV ,
CovC_IL_ALAE_NC_FL ,
CovC_IL_ALAE_NC_AO ,
CovC_IL_ALAE_Cat_Fire ,
CovC_IL_ALAE_Cat_AO ,
CovD_IL_ALAE_NC_Water ,
CovD_IL_ALAE_NC_WH ,
CovD_IL_ALAE_NC_TV ,
CovD_IL_ALAE_NC_FL ,
CovD_IL_ALAE_NC_AO ,
CovD_IL_ALAE_Cat_Fire ,
CovD_IL_ALAE_Cat_AO ,
CovE_IL_ALAE_NC_Water ,
CovE_IL_ALAE_NC_WH ,
CovE_IL_ALAE_NC_TV ,
CovE_IL_ALAE_NC_FL ,
CovE_IL_ALAE_NC_AO ,
CovE_IL_ALAE_Cat_Fire ,
CovE_IL_ALAE_Cat_AO ,
CovF_IL_ALAE_NC_Water ,
CovF_IL_ALAE_NC_WH ,
CovF_IL_ALAE_NC_TV ,
CovF_IL_ALAE_NC_FL ,
CovF_IL_ALAE_NC_AO ,
CovF_IL_ALAE_Cat_Fire ,
CovF_IL_ALAE_Cat_AO ,
LIAB_IL_ALAE_NC_Water ,
LIAB_IL_ALAE_NC_WH ,
LIAB_IL_ALAE_NC_TV ,
LIAB_IL_ALAE_NC_FL ,
LIAB_IL_ALAE_NC_AO ,
LIAB_IL_ALAE_Cat_Fire ,
LIAB_IL_ALAE_Cat_AO ,
CovA_IC_NC_Water ,
CovA_IC_NC_WH ,
CovA_IC_NC_TV ,
CovA_IC_NC_FL ,
CovA_IC_NC_AO ,
CovA_IC_Cat_Fire ,
CovA_IC_Cat_AO ,
CovB_IC_NC_Water ,
CovB_IC_NC_WH ,
CovB_IC_NC_TV ,
CovB_IC_NC_FL ,
CovB_IC_NC_AO ,
CovB_IC_Cat_Fire ,
CovB_IC_Cat_AO ,
CovC_IC_NC_Water ,
CovC_IC_NC_WH ,
CovC_IC_NC_TV ,
CovC_IC_NC_FL ,
CovC_IC_NC_AO ,
CovC_IC_Cat_Fire ,
CovC_IC_Cat_AO ,
CovD_IC_NC_Water ,
CovD_IC_NC_WH ,
CovD_IC_NC_TV ,
CovD_IC_NC_FL ,
CovD_IC_NC_AO ,
CovD_IC_Cat_Fire ,
CovD_IC_Cat_AO ,
CovE_IC_NC_Water ,
CovE_IC_NC_WH ,
CovE_IC_NC_TV ,
CovE_IC_NC_FL ,
CovE_IC_NC_AO ,
CovE_IC_Cat_Fire ,
CovE_IC_Cat_AO ,
CovF_IC_NC_Water ,
CovF_IC_NC_WH ,
CovF_IC_NC_TV ,
CovF_IC_NC_FL ,
CovF_IC_NC_AO ,
CovF_IC_Cat_Fire ,
CovF_IC_Cat_AO ,
LIAB_IC_NC_Water ,
LIAB_IC_NC_WH ,
LIAB_IC_NC_TV ,
LIAB_IC_NC_FL ,
LIAB_IC_NC_AO ,
LIAB_IC_Cat_Fire ,
LIAB_IC_Cat_AO ,
CovA_IC_DCCE_NC_Water ,
CovA_IC_DCCE_NC_WH ,
CovA_IC_DCCE_NC_TV ,
CovA_IC_DCCE_NC_FL ,
CovA_IC_DCCE_NC_AO ,
CovA_IC_DCCE_Cat_Fire ,
CovA_IC_DCCE_Cat_AO ,
CovB_IC_DCCE_NC_Water ,
CovB_IC_DCCE_NC_WH ,
CovB_IC_DCCE_NC_TV ,
CovB_IC_DCCE_NC_FL ,
CovB_IC_DCCE_NC_AO ,
CovB_IC_DCCE_Cat_Fire ,
CovB_IC_DCCE_Cat_AO ,
CovC_IC_DCCE_NC_Water ,
CovC_IC_DCCE_NC_WH ,
CovC_IC_DCCE_NC_TV ,
CovC_IC_DCCE_NC_FL ,
CovC_IC_DCCE_NC_AO ,
CovC_IC_DCCE_Cat_Fire ,
CovC_IC_DCCE_Cat_AO ,
CovD_IC_DCCE_NC_Water ,
CovD_IC_DCCE_NC_WH ,
CovD_IC_DCCE_NC_TV ,
CovD_IC_DCCE_NC_FL ,
CovD_IC_DCCE_NC_AO ,
CovD_IC_DCCE_Cat_Fire ,
CovD_IC_DCCE_Cat_AO ,
CovF_IC_DCCE_NC_Water ,
CovF_IC_DCCE_NC_WH ,
CovF_IC_DCCE_NC_TV ,
CovF_IC_DCCE_NC_FL ,
CovF_IC_DCCE_NC_AO ,
CovF_IC_DCCE_Cat_Fire ,
CovF_IC_DCCE_Cat_AO ,
LIAB_IC_DCCE_NC_Water ,
LIAB_IC_DCCE_NC_WH ,
LIAB_IC_DCCE_NC_TV ,
LIAB_IC_DCCE_NC_FL ,
LIAB_IC_DCCE_NC_AO ,
LIAB_IC_DCCE_Cat_Fire ,
LIAB_IC_DCCE_Cat_AO ,
CovA_IC_ALAE_NC_Water ,
CovA_IC_ALAE_NC_WH ,
CovA_IC_ALAE_NC_TV ,
CovA_IC_ALAE_NC_FL ,
CovA_IC_ALAE_NC_AO ,
CovA_IC_ALAE_Cat_Fire ,
CovA_IC_ALAE_Cat_AO ,
CovB_IC_ALAE_NC_Water ,
CovB_IC_ALAE_NC_WH ,
CovB_IC_ALAE_NC_TV ,
CovB_IC_ALAE_NC_FL ,
CovB_IC_ALAE_NC_AO ,
CovB_IC_ALAE_Cat_Fire ,
CovB_IC_ALAE_Cat_AO ,
CovC_IC_ALAE_NC_Water ,
CovC_IC_ALAE_NC_WH ,
CovC_IC_ALAE_NC_TV ,
CovC_IC_ALAE_NC_FL ,
CovC_IC_ALAE_NC_AO ,
CovC_IC_ALAE_Cat_Fire ,
CovC_IC_ALAE_Cat_AO ,
CovD_IC_ALAE_NC_Water ,
CovD_IC_ALAE_NC_WH ,
CovD_IC_ALAE_NC_TV ,
CovD_IC_ALAE_NC_FL ,
CovD_IC_ALAE_NC_AO ,
CovD_IC_ALAE_Cat_Fire ,
CovD_IC_ALAE_Cat_AO ,
CovE_IC_ALAE_NC_Water ,
CovE_IC_ALAE_NC_WH ,
CovE_IC_ALAE_NC_TV ,
CovE_IC_ALAE_NC_FL ,
CovE_IC_ALAE_NC_AO ,
CovE_IC_ALAE_Cat_Fire ,
CovE_IC_ALAE_Cat_AO ,
CovF_IC_ALAE_NC_Water ,
CovF_IC_ALAE_NC_WH ,
CovF_IC_ALAE_NC_TV ,
CovF_IC_ALAE_NC_FL ,
CovF_IC_ALAE_NC_AO ,
CovF_IC_ALAE_Cat_Fire ,
CovF_IC_ALAE_Cat_AO ,
LIAB_IC_ALAE_NC_Water ,
LIAB_IC_ALAE_NC_WH ,
LIAB_IC_ALAE_NC_TV ,
LIAB_IC_ALAE_NC_FL ,
LIAB_IC_ALAE_NC_AO ,
LIAB_IC_ALAE_Cat_Fire ,
LIAB_IC_ALAE_Cat_AO ,
isnull(CovA_FL,0) CovA_FL,
isnull(CovA_SF,0) CovA_SF,
isnull(CovA_EC,0) CovA_EC,
isnull(CovC_FL,0) CovC_FL,
isnull(CovC_SF,0) CovC_SF,
isnull(CovC_EC,0) CovC_EC,
pLoadDate LoadDate
from tmp_final f
left outer join tmp_all_wp wp
on f.policy_uniqueid=wp.policy_uniqueid
and f.SystemIdStart=wp.systemid
and f.Risk_uniqueid=wp.risk_uniqueid;
drop table if exists tmp_final;
drop table if exists tmp_all_wp;
END;


$$
;
