drop  table if exists external_data_modeling.auto;									
									
create external table external_data_modeling.auto(									
policynumber	VARCHAR(50) ,								
policy_uniqueid	VARCHAR(20) ,								
vin	VARCHAR(100) ,								
vehicle_uniqueid	VARCHAR(250) ,								
riskcd	INTEGER ,								
risktypecd	VARCHAR(255) ,								
driver	VARCHAR(255) ,								
drivernumber	INTEGER ,								
driverparentid	VARCHAR(250) ,								
cal_year	INTEGER ,								
startdate	DATE ,								
enddate	TIMESTAMP ,								
startdatetm	TIMESTAMP ,								
enddatetm	TIMESTAMP ,								
ecy	NUMERIC(25,	4)	,						
coverage	VARCHAR(6) ,								
limit1	VARCHAR(50) ,								
limit2	VARCHAR(50) ,								
deductible	VARCHAR(50) ,								
wp	NUMERIC(38,	2)	,						
ep	NUMERIC(38,	6)	,						
coll_deductible	VARCHAR(50) ,								
comp_deductible	VARCHAR(50) ,								
bi_limit1	VARCHAR(50) ,								
bi_limit2	VARCHAR(50) ,								
umbi_limit1	VARCHAR(50) ,								
umbi_limit2	VARCHAR(50) ,								
pd_limit1	VARCHAR(50) ,								
pd_limit2	VARCHAR(50) ,								
cntveh	INTEGER ,								
cntdrv	INTEGER ,								
cntnondrv	INTEGER ,								
cntexcludeddrv	INTEGER ,								
mindriverage	INTEGER ,								
extra_vehicles	VARCHAR(3) ,								
companycd	VARCHAR(50) ,								
carriercd	VARCHAR(100) ,								
programind	VARCHAR(255) ,								
previouscarriercd	VARCHAR(255) ,								
policyneworrenewal	VARCHAR(7) ,								
renewaltermcd	VARCHAR(255) ,								
effectivedate	DATE ,								
expirationdate	DATE ,								
inceptiondt	TIMESTAMP ,								
persistencydiscountdt	DATE ,								
producercode	VARCHAR(50) ,								
producername	VARCHAR(255) ,								
produceraddress	VARCHAR(510) ,								
producercity	VARCHAR(80) ,								
producerstate	VARCHAR(50) ,								
producerpostalcode	VARCHAR(20) ,								
producer_status	VARCHAR(10) ,								
territory	VARCHAR(50) ,								
multipolicydiscountind	VARCHAR(3) ,								
multipolicydiscountind_value	VARCHAR(255) ,								
homerelatedpolicynumber	VARCHAR(255) ,								
umbrellarelatedpolicynumber	VARCHAR(255) ,								
multicardiscountind	VARCHAR(3) ,								
cseemployeediscountind	VARCHAR(255) ,								
installmentfee	VARCHAR(255) ,								
nsffee	VARCHAR(255) ,								
latefee	VARCHAR(255) ,								
liabilityreductionind	VARCHAR(255) ,								
fullpaydiscountind	VARCHAR(255) ,								
twopaydiscountind	VARCHAR(255) ,								
eftdiscount	VARCHAR(3) ,								
persistency	INTEGER ,								
policyyear	INTEGER ,								
vehicleinceptiondate	DATE ,								
state	VARCHAR(255) ,								
county	VARCHAR(255) ,								
postalcode	VARCHAR(255) ,								
city	VARCHAR(255) ,								
addr1	VARCHAR(1023) ,								
addr2	VARCHAR(255) ,								
garagaddrflg	VARCHAR(3) ,								
garagpostalcode	VARCHAR(255) ,								
garagpostalcodeflg	VARCHAR(3) ,								
vehbodytypecd	VARCHAR(255) ,								
performancecd	VARCHAR(255) ,								
modelyr	VARCHAR(10) ,								
vehusecd	VARCHAR(255) ,								
estimatedannualdistance	INTEGER ,								
estimatedworkdistance	INTEGER ,								
odometerreading	VARCHAR(10) ,								
weekspermonthdriven	VARCHAR(255) ,								
daysperweekdriven	VARCHAR(255) ,								
manufacturer	VARCHAR(255) ,								
neworusedind	VARCHAR(255) ,								
antitheftcd	VARCHAR(255) ,								
restraintcd	VARCHAR(255) ,								
towingandlaborind	VARCHAR(255) ,								
rentalreimbursementind	VARCHAR(255) ,								
medicalpartsaccessibility	VARCHAR(4) ,								
mileage	VARCHAR(12) ,								
titlehistoryissue	VARCHAR(3) ,								
californiarecentmileage	INTEGER ,								
recentaveragemileage	INTEGER ,								
averagemileage	INTEGER ,								
modeledannualmileage	INTEGER ,								
last_owner_average_miles	INTEGER ,								
last_owner_recent_annual_mileage	INTEGER ,								
last_owner_government_recent_annual_mileage	INTEGER ,								
estimated_current_mileage	INTEGER ,								
annual_mileage_estimate	INTEGER ,								
salvage	VARCHAR(3) ,								
matchcarfax	VARCHAR(51) ,								
carfaxsource	VARCHAR(50) ,								
classcd	VARCHAR(255) ,								
ratingvalue	VARCHAR(255) ,								
cmpratingvalue	VARCHAR(255) ,								
colratingvalue	VARCHAR(255) ,								
liabilityratingvalue	VARCHAR(255) ,								
medpayratingvalue	VARCHAR(255) ,								
racmpratingvalue	VARCHAR(255) ,								
racolratingvalue	VARCHAR(255) ,								
rabiratingsymbol	VARCHAR(255) ,								
rapdratingsymbol	VARCHAR(255) ,								
ramedpayratingsymbol	VARCHAR(255) ,								
garageterritory	INTEGER ,								
daylightrunninglightsind	VARCHAR(255) ,								
costnewamt	NUMERIC(28,	6)	,						
statedamt	NUMERIC(28,	6)	,						
statedamtind	VARCHAR(255) ,								
fullglasscovind	VARCHAR(3) ,								
vehicle_value	NUMERIC(28,	6)	,						
liabilityonlyflg	VARCHAR(3) ,								
componlyflg	VARCHAR(3) ,								
driverinceptiondate	DATE ,								
licensenumber	VARCHAR(255) ,								
birthdt	TIMESTAMP ,								
gendercd	VARCHAR(255) ,								
maritalstatuscd	VARCHAR(255) ,								
acci_pointschargedterm	INTEGER ,								
viol_pointschargedterm	INTEGER ,								
susp_pointschargedterm	INTEGER ,								
other_pointschargedterm	INTEGER ,								
driverstatuscd	VARCHAR(255) ,								
drivertypecd	VARCHAR(255) ,								
licensedt	TIMESTAMP ,								
licensedstateprovcd	VARCHAR(255) ,								
newtostateind	VARCHAR(255) ,								
scholasticdiscountind	VARCHAR(255) ,								
gooddriverind	VARCHAR(255) ,								
maturedriverind	VARCHAR(255) ,								
occupationclasscd	VARCHAR(255) ,								
mvrstatusdt	TIMESTAMP ,								
mvrstatus	VARCHAR(255) ,								
newteenexpirationdt	DATE ,								
drivertrainingind	VARCHAR(255) ,								
viol_pointscharged_adj	INTEGER ,								
acci_pointscharged_adj	INTEGER ,								
missedviolationpoints	INTEGER ,								
acci5yr	INTEGER ,								
acci7yr	INTEGER ,								
pointscharged	INTEGER ,								
driverage	BIGINT ,								
driverlicenseage	BIGINT ,								
excess_veh_ind	VARCHAR(3) ,								
insurancescore	VARCHAR(255) ,								
overriddeninsurancescore	VARCHAR(255) ,								
insurancescorevalue	VARCHAR(5) ,								
ratepageeffectivedt	TIMESTAMP ,								
insscoretiervalueband	VARCHAR(20) ,								
applieddt	DATE ,								
financialstabilitytier	VARCHAR(20) ,								
excludeddrvflg	VARCHAR(3) ,								
claim_count_le500	NUMERIC(12,	2)	,						
claim_count_1000	NUMERIC(12,	2)	,						
claim_count_1500	NUMERIC(12,	2)	,						
claim_count_2000	NUMERIC(12,	2)	,						
claim_count_2500	NUMERIC(12,	2)	,						
claim_count_5k	NUMERIC(12,	2)	,						
claim_count_10k	NUMERIC(12,	2)	,						
claim_count_25k	NUMERIC(12,	2)	,						
claim_count_50k	NUMERIC(12,	2)	,						
claim_count_100k	NUMERIC(12,	2)	,						
claim_count_250k	NUMERIC(12,	2)	,						
claim_count_500k	NUMERIC(12,	2)	,						
claim_count_750k	NUMERIC(12,	2)	,						
claim_count_1m	NUMERIC(12,	2)	,						
claim_count	NUMERIC(12,	2)	,						
nc_inc_loss_le500	NUMERIC(38,	2)	,						
nc_inc_loss_1000	NUMERIC(38,	2)	,						
nc_inc_loss_1500	NUMERIC(38,	2)	,						
nc_inc_loss_2000	NUMERIC(38,	2)	,						
nc_inc_loss_2500	NUMERIC(38,	2)	,						
nc_inc_loss_5k	NUMERIC(38,	2)	,						
nc_inc_loss_10k	NUMERIC(38,	2)	,						
nc_inc_loss_25k	NUMERIC(38,	2)	,						
nc_inc_loss_50k	NUMERIC(38,	2)	,						
nc_inc_loss_100k	NUMERIC(38,	2)	,						
nc_inc_loss_250k	NUMERIC(38,	2)	,						
nc_inc_loss_500k	NUMERIC(38,	2)	,						
nc_inc_loss_750k	NUMERIC(38,	2)	,						
nc_inc_loss_1m	NUMERIC(38,	2)	,						
nc_inc_loss	NUMERIC(38,	2)	,						
cat_inc_loss_le500	NUMERIC(38,	2)	,						
cat_inc_loss_1000	NUMERIC(38,	2)	,						
cat_inc_loss_1500	NUMERIC(38,	2)	,						
cat_inc_loss_2000	NUMERIC(38,	2)	,						
cat_inc_loss_2500	NUMERIC(38,	2)	,						
cat_inc_loss_5k	NUMERIC(38,	2)	,						
cat_inc_loss_10k	NUMERIC(38,	2)	,						
cat_inc_loss_25k	NUMERIC(38,	2)	,						
cat_inc_loss_50k	NUMERIC(38,	2)	,						
cat_inc_loss_100k	NUMERIC(38,	2)	,						
cat_inc_loss_250k	NUMERIC(38,	2)	,						
cat_inc_loss_500k	NUMERIC(38,	2)	,						
cat_inc_loss_750k	NUMERIC(38,	2)	,						
cat_inc_loss_1m	NUMERIC(38,	2)	,						
cat_inc_loss	NUMERIC(38,	2)	,						
nc_inc_loss_dcce_le500	NUMERIC(38,	2)	,						
nc_inc_loss_dcce_1000	NUMERIC(38,	2)	,						
nc_inc_loss_dcce_1500	NUMERIC(38,	2)	,						
nc_inc_loss_dcce_2000	NUMERIC(38,	2)	,						
nc_inc_loss_dcce_2500	NUMERIC(38,	2)	,						
nc_inc_loss_dcce_5k	NUMERIC(38,	2)	,						
nc_inc_loss_dcce_10k	NUMERIC(38,	2)	,						
nc_inc_loss_dcce_25k	NUMERIC(38,	2)	,						
nc_inc_loss_dcce_50k	NUMERIC(38,	2)	,						
nc_inc_loss_dcce_100k	NUMERIC(38,	2)	,						
nc_inc_loss_dcce_250k	NUMERIC(38,	2)	,						
nc_inc_loss_dcce_500k	NUMERIC(38,	2)	,						
nc_inc_loss_dcce_750k	NUMERIC(38,	2)	,						
nc_inc_loss_dcce_1m	NUMERIC(38,	2)	,						
nc_inc_loss_dcce	NUMERIC(38,	2)	,						
cat_inc_loss_dcce_le500	NUMERIC(38,	2)	,						
cat_inc_loss_dcce_1000	NUMERIC(38,	2)	,						
cat_inc_loss_dcce_1500	NUMERIC(38,	2)	,						
cat_inc_loss_dcce_2000	NUMERIC(38,	2)	,						
cat_inc_loss_dcce_2500	NUMERIC(38,	2)	,						
cat_inc_loss_dcce_5k	NUMERIC(38,	2)	,						
cat_inc_loss_dcce_10k	NUMERIC(38,	2)	,						
cat_inc_loss_dcce_25k	NUMERIC(38,	2)	,						
cat_inc_loss_dcce_50k	NUMERIC(38,	2)	,						
cat_inc_loss_dcce_100k	NUMERIC(38,	2)	,						
cat_inc_loss_dcce_250k	NUMERIC(38,	2)	,						
cat_inc_loss_dcce_500k	NUMERIC(38,	2)	,						
cat_inc_loss_dcce_750k	NUMERIC(38,	2)	,						
cat_inc_loss_dcce_1m	NUMERIC(38,	2)	,						
cat_inc_loss_dcce	NUMERIC(38,	2)	,						
bilossinc1530	INTEGER ,								
umbilossinc1530	INTEGER ,								
uimbilossinc1530	INTEGER ,								
qualityflgreplacedvin	VARCHAR(3) ,								
qualityflgreplaceddriver	VARCHAR(3) ,								
qualityclaimokflg	INTEGER ,								
qualityclaimunknownvinflg	INTEGER ,								
qualityclaimunknownvinnotlisteddriverflg	INTEGER ,								
qualityclaimpolicytermjoinflg	INTEGER ,								
loaddate	TIMESTAMP 								
)									
partitioned by (month_id INTEGER)									
stored as PARQUET									
location  's3://cse-bi/RedshiftSpectrum/Modeling/Auto/'									
TABLE PROPERTIES ( 'write.parallel'='on' );									
									
									
									
